#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManagerWeb.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FleetManager")]
	public partial class CarFleetDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCarFleet(CarFleet instance);
    partial void UpdateCarFleet(CarFleet instance);
    partial void DeleteCarFleet(CarFleet instance);
    #endregion
		
		public CarFleetDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FleetManagerConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CarFleetDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarFleetDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarFleetDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarFleetDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CarFleet> CarFleets
		{
			get
			{
				return this.GetTable<CarFleet>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CountCarFleet")]
		public ISingleResult<CountCarFleetResult> CountCarFleet()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CountCarFleetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteCarFleet")]
		public ISingleResult<DeleteCarFleetResult> DeleteCarFleet([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdList", DbType="NVarChar(MAX)")] string idList, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeletedBy", DbType="BigInt")] System.Nullable<long> deletedBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="BigInt")] System.Nullable<long> pageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idList, deletedBy, pageId);
			return ((ISingleResult<DeleteCarFleetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetCarFleetById")]
		public ISingleResult<GetCarFleetByIdResult> GetCarFleetById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<GetCarFleetByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertOrUpdateCarFleet")]
		public ISingleResult<InsertOrUpdateCarFleetResult> InsertOrUpdateCarFleet(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Owner_Id", DbType="Int")] System.Nullable<int> owner_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code", DbType="NVarChar(10)")] string code, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Reg", DbType="NVarChar(10)")] string reg, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Desc", DbType="NVarChar(50)")] string desc, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Color_Id", DbType="Int")] System.Nullable<int> color_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fuel_Type", DbType="NVarChar(1)")] string fuel_Type, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Last_Trip", DbType="NVarChar(30)")] string last_Trip, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Last_Km", DbType="Int")] System.Nullable<int> last_Km, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Last_Location", DbType="NVarChar(100)")] string last_Location, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Id", DbType="Int")] System.Nullable<int> user_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="Int")] System.Nullable<int> pageId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FleetModels_Id", DbType="Int")] System.Nullable<int> fleetModels_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FleetMakes_Id", DbType="Int")] System.Nullable<int> fleetMakes_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_1", DbType="Int")] System.Nullable<int> id_1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_1_1", DbType="Int")] System.Nullable<int> id_1_1)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, owner_Id, code, reg, desc, color_Id, fuel_Type, last_Trip, last_Km, last_Location, user_Id, pageId, fleetModels_Id, fleetMakes_Id, id_1, id_1_1);
			return ((ISingleResult<InsertOrUpdateCarFleetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SearchCarFleet")]
		public ISingleResult<SearchCarFleetResult> SearchCarFleet([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rows", DbType="Int")] System.Nullable<int> rows, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Page", DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sort", DbType="NVarChar(50)")] string sort, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TripStartDate", DbType="NVarChar(15)")] string tripStartDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TripEndDate", DbType="NVarChar(15)")] string tripEndDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search", DbType="NVarChar(50)")] string search)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rows, page, sort, tripStartDate, tripEndDate, search);
			return ((ISingleResult<SearchCarFleetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetCarFleetAll")]
		public ISingleResult<GetCarFleetAllResult> GetCarFleetAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetCarFleetAllResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CarFleet")]
	public partial class CarFleet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Owner_Id;
		
		private string _Code;
		
		private string _Reg;
		
		private string _Desc;
		
		private long _Color_Id;
		
		private string _Fuel_Type;
		
		private System.DateTime _Last_Trip;
		
		private int _Last_Km;
		
		private string _Last_Location;
		
		private System.Nullable<int> _Id_1;
		
		private System.Nullable<int> _Id_1_1;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<int> _DeletedBy;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private System.Nullable<long> _FleetModels_Id;
		
		private System.Nullable<long> _FleetMakes_Id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnOwner_IdChanging(int value);
    partial void OnOwner_IdChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnRegChanging(string value);
    partial void OnRegChanged();
    partial void OnDescChanging(string value);
    partial void OnDescChanged();
    partial void OnColor_IdChanging(long value);
    partial void OnColor_IdChanged();
    partial void OnFuel_TypeChanging(string value);
    partial void OnFuel_TypeChanged();
    partial void OnLast_TripChanging(System.DateTime value);
    partial void OnLast_TripChanged();
    partial void OnLast_KmChanging(int value);
    partial void OnLast_KmChanged();
    partial void OnLast_LocationChanging(string value);
    partial void OnLast_LocationChanged();
    partial void OnId_1Changing(System.Nullable<int> value);
    partial void OnId_1Changed();
    partial void OnId_1_1Changing(System.Nullable<int> value);
    partial void OnId_1_1Changed();
    partial void OnIsDeletedChanging(System.Nullable<bool> value);
    partial void OnIsDeletedChanged();
    partial void OnDeletedByChanging(System.Nullable<int> value);
    partial void OnDeletedByChanged();
    partial void OnDeletedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnDeletedOnChanged();
    partial void OnFleetModels_IdChanging(System.Nullable<long> value);
    partial void OnFleetModels_IdChanged();
    partial void OnFleetMakes_IdChanging(System.Nullable<long> value);
    partial void OnFleetMakes_IdChanged();
    #endregion
		
		public CarFleet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owner_Id", DbType="Int NOT NULL")]
		public int Owner_Id
		{
			get
			{
				return this._Owner_Id;
			}
			set
			{
				if ((this._Owner_Id != value))
				{
					this.OnOwner_IdChanging(value);
					this.SendPropertyChanging();
					this._Owner_Id = value;
					this.SendPropertyChanged("Owner_Id");
					this.OnOwner_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(10)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reg", DbType="NVarChar(10)")]
		public string Reg
		{
			get
			{
				return this._Reg;
			}
			set
			{
				if ((this._Reg != value))
				{
					this.OnRegChanging(value);
					this.SendPropertyChanging();
					this._Reg = value;
					this.SendPropertyChanged("Reg");
					this.OnRegChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Desc]", Storage="_Desc", DbType="NVarChar(50)")]
		public string Desc
		{
			get
			{
				return this._Desc;
			}
			set
			{
				if ((this._Desc != value))
				{
					this.OnDescChanging(value);
					this.SendPropertyChanging();
					this._Desc = value;
					this.SendPropertyChanged("Desc");
					this.OnDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color_Id", DbType="BigInt NOT NULL")]
		public long Color_Id
		{
			get
			{
				return this._Color_Id;
			}
			set
			{
				if ((this._Color_Id != value))
				{
					this.OnColor_IdChanging(value);
					this.SendPropertyChanging();
					this._Color_Id = value;
					this.SendPropertyChanged("Color_Id");
					this.OnColor_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fuel_Type", DbType="NVarChar(1)")]
		public string Fuel_Type
		{
			get
			{
				return this._Fuel_Type;
			}
			set
			{
				if ((this._Fuel_Type != value))
				{
					this.OnFuel_TypeChanging(value);
					this.SendPropertyChanging();
					this._Fuel_Type = value;
					this.SendPropertyChanged("Fuel_Type");
					this.OnFuel_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Trip", DbType="DateTime NOT NULL")]
		public System.DateTime Last_Trip
		{
			get
			{
				return this._Last_Trip;
			}
			set
			{
				if ((this._Last_Trip != value))
				{
					this.OnLast_TripChanging(value);
					this.SendPropertyChanging();
					this._Last_Trip = value;
					this.SendPropertyChanged("Last_Trip");
					this.OnLast_TripChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Km", DbType="Int NOT NULL")]
		public int Last_Km
		{
			get
			{
				return this._Last_Km;
			}
			set
			{
				if ((this._Last_Km != value))
				{
					this.OnLast_KmChanging(value);
					this.SendPropertyChanging();
					this._Last_Km = value;
					this.SendPropertyChanged("Last_Km");
					this.OnLast_KmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Location", DbType="NVarChar(100)")]
		public string Last_Location
		{
			get
			{
				return this._Last_Location;
			}
			set
			{
				if ((this._Last_Location != value))
				{
					this.OnLast_LocationChanging(value);
					this.SendPropertyChanging();
					this._Last_Location = value;
					this.SendPropertyChanged("Last_Location");
					this.OnLast_LocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_1", DbType="Int")]
		public System.Nullable<int> Id_1
		{
			get
			{
				return this._Id_1;
			}
			set
			{
				if ((this._Id_1 != value))
				{
					this.OnId_1Changing(value);
					this.SendPropertyChanging();
					this._Id_1 = value;
					this.SendPropertyChanged("Id_1");
					this.OnId_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_1_1", DbType="Int")]
		public System.Nullable<int> Id_1_1
		{
			get
			{
				return this._Id_1_1;
			}
			set
			{
				if ((this._Id_1_1 != value))
				{
					this.OnId_1_1Changing(value);
					this.SendPropertyChanging();
					this._Id_1_1 = value;
					this.SendPropertyChanged("Id_1_1");
					this.OnId_1_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="Int")]
		public System.Nullable<int> DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this.OnDeletedByChanging(value);
					this.SendPropertyChanging();
					this._DeletedBy = value;
					this.SendPropertyChanged("DeletedBy");
					this.OnDeletedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this.OnDeletedOnChanging(value);
					this.SendPropertyChanging();
					this._DeletedOn = value;
					this.SendPropertyChanged("DeletedOn");
					this.OnDeletedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FleetModels_Id", DbType="BigInt")]
		public System.Nullable<long> FleetModels_Id
		{
			get
			{
				return this._FleetModels_Id;
			}
			set
			{
				if ((this._FleetModels_Id != value))
				{
					this.OnFleetModels_IdChanging(value);
					this.SendPropertyChanging();
					this._FleetModels_Id = value;
					this.SendPropertyChanged("FleetModels_Id");
					this.OnFleetModels_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FleetMakes_Id", DbType="BigInt")]
		public System.Nullable<long> FleetMakes_Id
		{
			get
			{
				return this._FleetMakes_Id;
			}
			set
			{
				if ((this._FleetMakes_Id != value))
				{
					this.OnFleetMakes_IdChanging(value);
					this.SendPropertyChanging();
					this._FleetMakes_Id = value;
					this.SendPropertyChanged("FleetMakes_Id");
					this.OnFleetMakes_IdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class CountCarFleetResult
	{
		
		private System.Nullable<int> _Result;
		
		public CountCarFleetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int")]
		public System.Nullable<int> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class DeleteCarFleetResult
	{
		
		private int _TotalReference;
		
		private string _Name;
		
		public DeleteCarFleetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalReference", DbType="Int NOT NULL")]
		public int TotalReference
		{
			get
			{
				return this._TotalReference;
			}
			set
			{
				if ((this._TotalReference != value))
				{
					this._TotalReference = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class GetCarFleetByIdResult
	{
		
		private int _ID;
		
		private int _Owner_Id;
		
		private string _Code;
		
		private string _Reg;
		
		private string _Description;
		
		private int _Color_Id;
		
		private string _Fuel_Type;
		
		private string _Last_Trip;
		
		private int _Last_Km;
		
		private string _Last_Location;
		
		private System.Nullable<long> _FleetModels_Id;
		
		private System.Nullable<int> _FleetMakes_Id;
		
		private string _Make;
		
		private string _Model;
		
		private System.Nullable<int> _Id_1;
		
		private System.Nullable<int> _Id_1_1;
		
		public GetCarFleetByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owner_Id", DbType="Int NOT NULL")]
		public int Owner_Id
		{
			get
			{
				return this._Owner_Id;
			}
			set
			{
				if ((this._Owner_Id != value))
				{
					this._Owner_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(10)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reg", DbType="NVarChar(10)")]
		public string Reg
		{
			get
			{
				return this._Reg;
			}
			set
			{
				if ((this._Reg != value))
				{
					this._Reg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color_Id", DbType="Int NOT NULL")]
		public int Color_Id
		{
			get
			{
				return this._Color_Id;
			}
			set
			{
				if ((this._Color_Id != value))
				{
					this._Color_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fuel_Type", DbType="NVarChar(1)")]
		public string Fuel_Type
		{
			get
			{
				return this._Fuel_Type;
			}
			set
			{
				if ((this._Fuel_Type != value))
				{
					this._Fuel_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Trip", DbType="NVarChar(12)")]
		public string Last_Trip
		{
			get
			{
				return this._Last_Trip;
			}
			set
			{
				if ((this._Last_Trip != value))
				{
					this._Last_Trip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Km", DbType="Int NOT NULL")]
		public int Last_Km
		{
			get
			{
				return this._Last_Km;
			}
			set
			{
				if ((this._Last_Km != value))
				{
					this._Last_Km = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Location", DbType="NVarChar(100)")]
		public string Last_Location
		{
			get
			{
				return this._Last_Location;
			}
			set
			{
				if ((this._Last_Location != value))
				{
					this._Last_Location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FleetModels_Id", DbType="BigInt")]
		public System.Nullable<long> FleetModels_Id
		{
			get
			{
				return this._FleetModels_Id;
			}
			set
			{
				if ((this._FleetModels_Id != value))
				{
					this._FleetModels_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FleetMakes_Id", DbType="Int")]
		public System.Nullable<int> FleetMakes_Id
		{
			get
			{
				return this._FleetMakes_Id;
			}
			set
			{
				if ((this._FleetMakes_Id != value))
				{
					this._FleetMakes_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Make", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Make
		{
			get
			{
				return this._Make;
			}
			set
			{
				if ((this._Make != value))
				{
					this._Make = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this._Model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_1", DbType="Int")]
		public System.Nullable<int> Id_1
		{
			get
			{
				return this._Id_1;
			}
			set
			{
				if ((this._Id_1 != value))
				{
					this._Id_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_1_1", DbType="Int")]
		public System.Nullable<int> Id_1_1
		{
			get
			{
				return this._Id_1_1;
			}
			set
			{
				if ((this._Id_1_1 != value))
				{
					this._Id_1_1 = value;
				}
			}
		}
	}
	
	public partial class InsertOrUpdateCarFleetResult
	{
		
		private int _InsertedId;
		
		public InsertOrUpdateCarFleetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedId", DbType="Int NOT NULL")]
		public int InsertedId
		{
			get
			{
				return this._InsertedId;
			}
			set
			{
				if ((this._InsertedId != value))
				{
					this._InsertedId = value;
				}
			}
		}
	}
	
	public partial class SearchCarFleetResult
	{
		
		private int _RowNum;
		
		private long _Id;
		
		private int _Owner_Id;
		
		private string _Code;
		
		private string _Reg;
		
		private string _Desc;
		
		private string _Color_Id;
		
		private string _Fuel_Type;
		
		private string _Last_Trip;
		
		private int _Last_Km;
		
		private string _Last_Location;
		
		private string _Make;
		
		private string _Model;
		
		private System.Nullable<int> _FleetMakes_Id;
		
		private System.Nullable<int> _FleetModels_Id;
		
		private int _Total;
		
		public SearchCarFleetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNum", DbType="Int NOT NULL")]
		public int RowNum
		{
			get
			{
				return this._RowNum;
			}
			set
			{
				if ((this._RowNum != value))
				{
					this._RowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owner_Id", DbType="Int NOT NULL")]
		public int Owner_Id
		{
			get
			{
				return this._Owner_Id;
			}
			set
			{
				if ((this._Owner_Id != value))
				{
					this._Owner_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(10)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reg", DbType="NVarChar(10)")]
		public string Reg
		{
			get
			{
				return this._Reg;
			}
			set
			{
				if ((this._Reg != value))
				{
					this._Reg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Desc]", Storage="_Desc", DbType="NVarChar(50)")]
		public string Desc
		{
			get
			{
				return this._Desc;
			}
			set
			{
				if ((this._Desc != value))
				{
					this._Desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color_Id", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Color_Id
		{
			get
			{
				return this._Color_Id;
			}
			set
			{
				if ((this._Color_Id != value))
				{
					this._Color_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fuel_Type", DbType="NVarChar(1)")]
		public string Fuel_Type
		{
			get
			{
				return this._Fuel_Type;
			}
			set
			{
				if ((this._Fuel_Type != value))
				{
					this._Fuel_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Trip", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string Last_Trip
		{
			get
			{
				return this._Last_Trip;
			}
			set
			{
				if ((this._Last_Trip != value))
				{
					this._Last_Trip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Km", DbType="Int NOT NULL")]
		public int Last_Km
		{
			get
			{
				return this._Last_Km;
			}
			set
			{
				if ((this._Last_Km != value))
				{
					this._Last_Km = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Location", DbType="NVarChar(100)")]
		public string Last_Location
		{
			get
			{
				return this._Last_Location;
			}
			set
			{
				if ((this._Last_Location != value))
				{
					this._Last_Location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Make", DbType="NVarChar(15)")]
		public string Make
		{
			get
			{
				return this._Make;
			}
			set
			{
				if ((this._Make != value))
				{
					this._Make = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="NVarChar(20)")]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this._Model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FleetMakes_Id", DbType="Int")]
		public System.Nullable<int> FleetMakes_Id
		{
			get
			{
				return this._FleetMakes_Id;
			}
			set
			{
				if ((this._FleetMakes_Id != value))
				{
					this._FleetMakes_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FleetModels_Id", DbType="Int")]
		public System.Nullable<int> FleetModels_Id
		{
			get
			{
				return this._FleetModels_Id;
			}
			set
			{
				if ((this._FleetModels_Id != value))
				{
					this._FleetModels_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int NOT NULL")]
		public int Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
	}
	
	public partial class GetCarFleetAllResult
	{
		
		private int _ID;
		
		private int _Owner_Id;
		
		private string _Code;
		
		private string _Reg;
		
		private string _Description;
		
		private long _Color_Id;
		
		private string _Fuel_Type;
		
		private string _Last_Trip;
		
		private int _Last_Km;
		
		private string _Last_Location;
		
		private System.Nullable<long> _FleetModels_Id;
		
		private System.Nullable<long> _FleetMakes_Id;
		
		private string _Make;
		
		private string _Model;
		
		private System.Nullable<int> _Id_1;
		
		private System.Nullable<int> _Id_1_1;
		
		public GetCarFleetAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owner_Id", DbType="Int NOT NULL")]
		public int Owner_Id
		{
			get
			{
				return this._Owner_Id;
			}
			set
			{
				if ((this._Owner_Id != value))
				{
					this._Owner_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(10)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reg", DbType="NVarChar(10)")]
		public string Reg
		{
			get
			{
				return this._Reg;
			}
			set
			{
				if ((this._Reg != value))
				{
					this._Reg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color_Id", DbType="BigInt NOT NULL")]
		public long Color_Id
		{
			get
			{
				return this._Color_Id;
			}
			set
			{
				if ((this._Color_Id != value))
				{
					this._Color_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fuel_Type", DbType="NVarChar(1)")]
		public string Fuel_Type
		{
			get
			{
				return this._Fuel_Type;
			}
			set
			{
				if ((this._Fuel_Type != value))
				{
					this._Fuel_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Trip", DbType="NVarChar(12)")]
		public string Last_Trip
		{
			get
			{
				return this._Last_Trip;
			}
			set
			{
				if ((this._Last_Trip != value))
				{
					this._Last_Trip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Km", DbType="Int NOT NULL")]
		public int Last_Km
		{
			get
			{
				return this._Last_Km;
			}
			set
			{
				if ((this._Last_Km != value))
				{
					this._Last_Km = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Location", DbType="NVarChar(100)")]
		public string Last_Location
		{
			get
			{
				return this._Last_Location;
			}
			set
			{
				if ((this._Last_Location != value))
				{
					this._Last_Location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FleetModels_Id", DbType="BigInt")]
		public System.Nullable<long> FleetModels_Id
		{
			get
			{
				return this._FleetModels_Id;
			}
			set
			{
				if ((this._FleetModels_Id != value))
				{
					this._FleetModels_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FleetMakes_Id", DbType="BigInt")]
		public System.Nullable<long> FleetMakes_Id
		{
			get
			{
				return this._FleetMakes_Id;
			}
			set
			{
				if ((this._FleetMakes_Id != value))
				{
					this._FleetMakes_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Make", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Make
		{
			get
			{
				return this._Make;
			}
			set
			{
				if ((this._Make != value))
				{
					this._Make = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this._Model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_1", DbType="Int")]
		public System.Nullable<int> Id_1
		{
			get
			{
				return this._Id_1;
			}
			set
			{
				if ((this._Id_1 != value))
				{
					this._Id_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_1_1", DbType="Int")]
		public System.Nullable<int> Id_1_1
		{
			get
			{
				return this._Id_1_1;
			}
			set
			{
				if ((this._Id_1_1 != value))
				{
					this._Id_1_1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
