#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManagerWeb.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SVLL_ETS")]
	public partial class CommonDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAAAAConfigSetting(AAAAConfigSetting instance);
    partial void UpdateAAAAConfigSetting(AAAAConfigSetting instance);
    partial void DeleteAAAAConfigSetting(AAAAConfigSetting instance);
    partial void InsertRolePermission(RolePermission instance);
    partial void UpdateRolePermission(RolePermission instance);
    partial void DeleteRolePermission(RolePermission instance);
    #endregion
		
		public CommonDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CommonDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CommonDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CommonDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AAAAConfigSetting> AAAAConfigSettings
		{
			get
			{
				return this.GetTable<AAAAConfigSetting>();
			}
		}
		
		public System.Data.Linq.Table<RolePermission> RolePermissions
		{
			get
			{
				return this.GetTable<RolePermission>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetPagePermission")]
		public ISingleResult<GetPagePermissionResult> GetPagePermission([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="BigInt")] System.Nullable<long> pageId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoleId", DbType="BigInt")] System.Nullable<long> roleId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageId, userId, roleId);
			return ((ISingleResult<GetPagePermissionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BranchWiseVehicle")]
		public ISingleResult<BranchWiseVehicleResult> BranchWiseVehicle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId);
			return ((ISingleResult<BranchWiseVehicleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertOrUpdateUserVehicleSubStatus")]
		public int InsertOrUpdateUserVehicleSubStatus([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubStatusIds", DbType="NVarChar(MAX)")] string subStatusIds, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), subStatusIds, userId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UserWiseVehicleSubStatus")]
		public ISingleResult<UserWiseVehicleSubStatusResult> UserWiseVehicleSubStatus([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StatusId1", DbType="BigInt")] System.Nullable<long> statusId1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StatusId2", DbType="BigInt")] System.Nullable<long> statusId2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId, statusId1, statusId2);
			return ((ISingleResult<UserWiseVehicleSubStatusResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CustomerWiseVehicleTransitCount")]
		public ISingleResult<CustomerWiseVehicleTransitCountResult> CustomerWiseVehicleTransitCount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerId", DbType="BigInt")] System.Nullable<long> customerId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId, customerId);
			return ((ISingleResult<CustomerWiseVehicleTransitCountResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CustomerWiseVehicle")]
		public ISingleResult<CustomerWiseVehicleResult> CustomerWiseVehicle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId);
			return ((ISingleResult<CustomerWiseVehicleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BranchWiseVehicleStatusCount")]
		public ISingleResult<BranchWiseVehicleStatusCountResult> BranchWiseVehicleStatusCount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StatusId", DbType="BigInt")] System.Nullable<long> statusId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="NVarChar(50)")] string fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToDate", DbType="NVarChar(50)")] string toDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId, statusId, fromDate, toDate);
			return ((ISingleResult<BranchWiseVehicleStatusCountResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SearchVehicleTrackingHistoryByBranchAndSubStatudId")]
		public ISingleResult<SearchVehicleTrackingHistoryByBranchAndSubStatudIdResult> SearchVehicleTrackingHistoryByBranchAndSubStatudId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrachId", DbType="BigInt")] System.Nullable<long> brachId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VehicleSubStauId", DbType="BigInt")] System.Nullable<long> vehicleSubStauId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rows", DbType="Int")] System.Nullable<int> rows, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Page", DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search", DbType="NVarChar(500)")] string search, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sort", DbType="NVarChar(50)")] string sort, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="NVarChar(50)")] string fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToDate", DbType="NVarChar(50)")] string toDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), brachId, vehicleSubStauId, rows, page, search, sort, fromDate, toDate);
			return ((ISingleResult<SearchVehicleTrackingHistoryByBranchAndSubStatudIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CustomerWiseVehicleStatusCount")]
		public ISingleResult<CustomerWiseVehicleStatusCountResult> CustomerWiseVehicleStatusCount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StatusId", DbType="BigInt")] System.Nullable<long> statusId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="NVarChar(50)")] string fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToDate", DbType="NVarChar(50)")] string toDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId, statusId, fromDate, toDate);
			return ((ISingleResult<CustomerWiseVehicleStatusCountResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SearchVehicleTrackingHistoryByCustomerAndSubStatudId")]
		public ISingleResult<SearchVehicleTrackingHistoryByCustomerAndSubStatudIdResult> SearchVehicleTrackingHistoryByCustomerAndSubStatudId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerId", DbType="BigInt")] System.Nullable<long> customerId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VehicleSubStauId", DbType="BigInt")] System.Nullable<long> vehicleSubStauId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rows", DbType="Int")] System.Nullable<int> rows, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Page", DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search", DbType="NVarChar(500)")] string search, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sort", DbType="NVarChar(50)")] string sort, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="NVarChar(50)")] string fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToDate", DbType="NVarChar(50)")] string toDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerId, vehicleSubStauId, rows, page, search, sort, fromDate, toDate);
			return ((ISingleResult<SearchVehicleTrackingHistoryByCustomerAndSubStatudIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BranchWiseVehicleTransitCount")]
		public ISingleResult<BranchWiseVehicleTransitCountResult> BranchWiseVehicleTransitCount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BranchId", DbType="BigInt")] System.Nullable<long> branchId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="NVarChar(100)")] string fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToDate", DbType="NVarChar(100)")] string toDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId, branchId, fromDate, toDate);
			return ((ISingleResult<BranchWiseVehicleTransitCountResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetBellCounter")]
		public ISingleResult<GetBellCounterResult> GetBellCounter([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId);
			return ((ISingleResult<GetBellCounterResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertOrUpdateBellCounter")]
		public int InsertOrUpdateBellCounter([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Action", DbType="NVarChar(MAX)")] string action, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecoredId", DbType="BigInt")] System.Nullable<long> recoredId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Controller", DbType="NVarChar(MAX)")] string controller, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageName", DbType="NVarChar(MAX)")] string pageName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Flag", DbType="Bit")] System.Nullable<bool> flag, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="BigInt")] System.Nullable<long> createdBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Remarks", DbType="NVarChar(200)")] string remarks)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, userId, action, recoredId, controller, pageName, flag, createdBy, remarks);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AAAAConfigSettings")]
	public partial class AAAAConfigSetting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _KeyName;
		
		private string _KeyValue;
		
		private string _KeyDescription;
		
		private string _Module;
		
		private System.DateTime _CreatedOn;
		
		private long _CreatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private System.Nullable<long> _UpdatedBy;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private System.Nullable<long> _DeletedBy;
		
		private bool _IsDeleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnKeyNameChanging(string value);
    partial void OnKeyNameChanged();
    partial void OnKeyValueChanging(string value);
    partial void OnKeyValueChanged();
    partial void OnKeyDescriptionChanging(string value);
    partial void OnKeyDescriptionChanged();
    partial void OnModuleChanging(string value);
    partial void OnModuleChanged();
    partial void OnCreatedOnChanging(System.DateTime value);
    partial void OnCreatedOnChanged();
    partial void OnCreatedByChanging(long value);
    partial void OnCreatedByChanged();
    partial void OnUpdatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedOnChanged();
    partial void OnUpdatedByChanging(System.Nullable<long> value);
    partial void OnUpdatedByChanged();
    partial void OnDeletedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnDeletedOnChanged();
    partial void OnDeletedByChanging(System.Nullable<long> value);
    partial void OnDeletedByChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public AAAAConfigSetting()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string KeyName
		{
			get
			{
				return this._KeyName;
			}
			set
			{
				if ((this._KeyName != value))
				{
					this.OnKeyNameChanging(value);
					this.SendPropertyChanging();
					this._KeyName = value;
					this.SendPropertyChanged("KeyName");
					this.OnKeyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyValue", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string KeyValue
		{
			get
			{
				return this._KeyValue;
			}
			set
			{
				if ((this._KeyValue != value))
				{
					this.OnKeyValueChanging(value);
					this.SendPropertyChanging();
					this._KeyValue = value;
					this.SendPropertyChanged("KeyValue");
					this.OnKeyValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyDescription", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string KeyDescription
		{
			get
			{
				return this._KeyDescription;
			}
			set
			{
				if ((this._KeyDescription != value))
				{
					this.OnKeyDescriptionChanging(value);
					this.SendPropertyChanging();
					this._KeyDescription = value;
					this.SendPropertyChanged("KeyDescription");
					this.OnKeyDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Module", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Module
		{
			get
			{
				return this._Module;
			}
			set
			{
				if ((this._Module != value))
				{
					this.OnModuleChanging(value);
					this.SendPropertyChanging();
					this._Module = value;
					this.SendPropertyChanged("Module");
					this.OnModuleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="BigInt NOT NULL")]
		public long CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="BigInt")]
		public System.Nullable<long> UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this.OnDeletedOnChanging(value);
					this.SendPropertyChanging();
					this._DeletedOn = value;
					this.SendPropertyChanged("DeletedOn");
					this.OnDeletedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="BigInt")]
		public System.Nullable<long> DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this.OnDeletedByChanging(value);
					this.SendPropertyChanging();
					this._DeletedBy = value;
					this.SendPropertyChanged("DeletedBy");
					this.OnDeletedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RolePermissions")]
	public partial class RolePermission : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private long _RoleId;
		
		private long _PageId;
		
		private bool _View_Right;
		
		private bool _Add_Right;
		
		private bool _Edit_Right;
		
		private bool _Delete_Right;
		
		private bool _Export_Right;
		
		private System.DateTime _CreatedOn;
		
		private long _CreatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private System.Nullable<long> _UpdatedBy;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private System.Nullable<long> _DeletedBy;
		
		private bool _IsDeleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnRoleIdChanging(long value);
    partial void OnRoleIdChanged();
    partial void OnPageIdChanging(long value);
    partial void OnPageIdChanged();
    partial void OnView_RightChanging(bool value);
    partial void OnView_RightChanged();
    partial void OnAdd_RightChanging(bool value);
    partial void OnAdd_RightChanged();
    partial void OnEdit_RightChanging(bool value);
    partial void OnEdit_RightChanged();
    partial void OnDelete_RightChanging(bool value);
    partial void OnDelete_RightChanged();
    partial void OnExport_RightChanging(bool value);
    partial void OnExport_RightChanged();
    partial void OnCreatedOnChanging(System.DateTime value);
    partial void OnCreatedOnChanged();
    partial void OnCreatedByChanging(long value);
    partial void OnCreatedByChanged();
    partial void OnUpdatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedOnChanged();
    partial void OnUpdatedByChanging(System.Nullable<long> value);
    partial void OnUpdatedByChanged();
    partial void OnDeletedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnDeletedOnChanged();
    partial void OnDeletedByChanging(System.Nullable<long> value);
    partial void OnDeletedByChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public RolePermission()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", DbType="BigInt NOT NULL")]
		public long RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				if ((this._RoleId != value))
				{
					this.OnRoleIdChanging(value);
					this.SendPropertyChanging();
					this._RoleId = value;
					this.SendPropertyChanged("RoleId");
					this.OnRoleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageId", DbType="BigInt NOT NULL")]
		public long PageId
		{
			get
			{
				return this._PageId;
			}
			set
			{
				if ((this._PageId != value))
				{
					this.OnPageIdChanging(value);
					this.SendPropertyChanging();
					this._PageId = value;
					this.SendPropertyChanged("PageId");
					this.OnPageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_View_Right", DbType="Bit NOT NULL")]
		public bool View_Right
		{
			get
			{
				return this._View_Right;
			}
			set
			{
				if ((this._View_Right != value))
				{
					this.OnView_RightChanging(value);
					this.SendPropertyChanging();
					this._View_Right = value;
					this.SendPropertyChanged("View_Right");
					this.OnView_RightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add_Right", DbType="Bit NOT NULL")]
		public bool Add_Right
		{
			get
			{
				return this._Add_Right;
			}
			set
			{
				if ((this._Add_Right != value))
				{
					this.OnAdd_RightChanging(value);
					this.SendPropertyChanging();
					this._Add_Right = value;
					this.SendPropertyChanged("Add_Right");
					this.OnAdd_RightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edit_Right", DbType="Bit NOT NULL")]
		public bool Edit_Right
		{
			get
			{
				return this._Edit_Right;
			}
			set
			{
				if ((this._Edit_Right != value))
				{
					this.OnEdit_RightChanging(value);
					this.SendPropertyChanging();
					this._Edit_Right = value;
					this.SendPropertyChanged("Edit_Right");
					this.OnEdit_RightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delete_Right", DbType="Bit NOT NULL")]
		public bool Delete_Right
		{
			get
			{
				return this._Delete_Right;
			}
			set
			{
				if ((this._Delete_Right != value))
				{
					this.OnDelete_RightChanging(value);
					this.SendPropertyChanging();
					this._Delete_Right = value;
					this.SendPropertyChanged("Delete_Right");
					this.OnDelete_RightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Export_Right", DbType="Bit NOT NULL")]
		public bool Export_Right
		{
			get
			{
				return this._Export_Right;
			}
			set
			{
				if ((this._Export_Right != value))
				{
					this.OnExport_RightChanging(value);
					this.SendPropertyChanging();
					this._Export_Right = value;
					this.SendPropertyChanged("Export_Right");
					this.OnExport_RightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="BigInt NOT NULL")]
		public long CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="BigInt")]
		public System.Nullable<long> UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this.OnDeletedOnChanging(value);
					this.SendPropertyChanging();
					this._DeletedOn = value;
					this.SendPropertyChanged("DeletedOn");
					this.OnDeletedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="BigInt")]
		public System.Nullable<long> DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this.OnDeletedByChanging(value);
					this.SendPropertyChanging();
					this._DeletedBy = value;
					this.SendPropertyChanged("DeletedBy");
					this.OnDeletedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetPagePermissionResult
	{
		
		private long _Id;
		
		private long _PageId;
		
		private long _RoleId;
		
		private string _ModuleName;
		
		private string _PageName;
		
		private string _DispalyName;
		
		private bool _View_Right;
		
		private bool _Add_Right;
		
		private bool _Edit_Right;
		
		private bool _Delete_Right;
		
		private bool _Export_Right;
		
		private bool _IsActive;
		
		public GetPagePermissionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageId", DbType="BigInt NOT NULL")]
		public long PageId
		{
			get
			{
				return this._PageId;
			}
			set
			{
				if ((this._PageId != value))
				{
					this._PageId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", DbType="BigInt NOT NULL")]
		public long RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				if ((this._RoleId != value))
				{
					this._RoleId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleName", DbType="NVarChar(50)")]
		public string ModuleName
		{
			get
			{
				return this._ModuleName;
			}
			set
			{
				if ((this._ModuleName != value))
				{
					this._ModuleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PageName
		{
			get
			{
				return this._PageName;
			}
			set
			{
				if ((this._PageName != value))
				{
					this._PageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DispalyName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DispalyName
		{
			get
			{
				return this._DispalyName;
			}
			set
			{
				if ((this._DispalyName != value))
				{
					this._DispalyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_View_Right", DbType="Bit NOT NULL")]
		public bool View_Right
		{
			get
			{
				return this._View_Right;
			}
			set
			{
				if ((this._View_Right != value))
				{
					this._View_Right = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Add_Right", DbType="Bit NOT NULL")]
		public bool Add_Right
		{
			get
			{
				return this._Add_Right;
			}
			set
			{
				if ((this._Add_Right != value))
				{
					this._Add_Right = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edit_Right", DbType="Bit NOT NULL")]
		public bool Edit_Right
		{
			get
			{
				return this._Edit_Right;
			}
			set
			{
				if ((this._Edit_Right != value))
				{
					this._Edit_Right = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delete_Right", DbType="Bit NOT NULL")]
		public bool Delete_Right
		{
			get
			{
				return this._Delete_Right;
			}
			set
			{
				if ((this._Delete_Right != value))
				{
					this._Delete_Right = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Export_Right", DbType="Bit NOT NULL")]
		public bool Export_Right
		{
			get
			{
				return this._Export_Right;
			}
			set
			{
				if ((this._Export_Right != value))
				{
					this._Export_Right = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
	}
	
	public partial class BranchWiseVehicleResult
	{
		
		private long _Id;
		
		private string _BranchName;
		
		private int _VehicleCount;
		
		public BranchWiseVehicleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string BranchName
		{
			get
			{
				return this._BranchName;
			}
			set
			{
				if ((this._BranchName != value))
				{
					this._BranchName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleCount", DbType="Int NOT NULL")]
		public int VehicleCount
		{
			get
			{
				return this._VehicleCount;
			}
			set
			{
				if ((this._VehicleCount != value))
				{
					this._VehicleCount = value;
				}
			}
		}
	}
	
	public partial class UserWiseVehicleSubStatusResult
	{
		
		private long _Id;
		
		private string _VehicleSubStatusName;
		
		private long _UserId;
		
		private string _VehicleStatusName;
		
		public UserWiseVehicleSubStatusResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleSubStatusName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string VehicleSubStatusName
		{
			get
			{
				return this._VehicleSubStatusName;
			}
			set
			{
				if ((this._VehicleSubStatusName != value))
				{
					this._VehicleSubStatusName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="BigInt NOT NULL")]
		public long UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleStatusName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string VehicleStatusName
		{
			get
			{
				return this._VehicleStatusName;
			}
			set
			{
				if ((this._VehicleStatusName != value))
				{
					this._VehicleStatusName = value;
				}
			}
		}
	}
	
	public partial class CustomerWiseVehicleTransitCountResult
	{
		
		private int _OnTime;
		
		private int _LateTransit;
		
		public CustomerWiseVehicleTransitCountResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnTime", DbType="Int NOT NULL")]
		public int OnTime
		{
			get
			{
				return this._OnTime;
			}
			set
			{
				if ((this._OnTime != value))
				{
					this._OnTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LateTransit", DbType="Int NOT NULL")]
		public int LateTransit
		{
			get
			{
				return this._LateTransit;
			}
			set
			{
				if ((this._LateTransit != value))
				{
					this._LateTransit = value;
				}
			}
		}
	}
	
	public partial class CustomerWiseVehicleResult
	{
		
		private long _Id;
		
		private string _CustomerName;
		
		private int _VehicleCount;
		
		public CustomerWiseVehicleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this._CustomerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleCount", DbType="Int NOT NULL")]
		public int VehicleCount
		{
			get
			{
				return this._VehicleCount;
			}
			set
			{
				if ((this._VehicleCount != value))
				{
					this._VehicleCount = value;
				}
			}
		}
	}
	
	public partial class BranchWiseVehicleStatusCountResult
	{
		
		private string _VehicleSubStatusName;
		
		private System.Nullable<int> _VehicleStatusCount;
		
		private System.Nullable<long> _VehicleSubStatusId;
		
		private System.Nullable<long> _BranchId;
		
		public BranchWiseVehicleStatusCountResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleSubStatusName", DbType="NVarChar(100)")]
		public string VehicleSubStatusName
		{
			get
			{
				return this._VehicleSubStatusName;
			}
			set
			{
				if ((this._VehicleSubStatusName != value))
				{
					this._VehicleSubStatusName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleStatusCount", DbType="Int")]
		public System.Nullable<int> VehicleStatusCount
		{
			get
			{
				return this._VehicleStatusCount;
			}
			set
			{
				if ((this._VehicleStatusCount != value))
				{
					this._VehicleStatusCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleSubStatusId", DbType="BigInt")]
		public System.Nullable<long> VehicleSubStatusId
		{
			get
			{
				return this._VehicleSubStatusId;
			}
			set
			{
				if ((this._VehicleSubStatusId != value))
				{
					this._VehicleSubStatusId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchId", DbType="BigInt")]
		public System.Nullable<long> BranchId
		{
			get
			{
				return this._BranchId;
			}
			set
			{
				if ((this._BranchId != value))
				{
					this._BranchId = value;
				}
			}
		}
	}
	
	public partial class SearchVehicleTrackingHistoryByBranchAndSubStatudIdResult
	{
		
		private int _RowNum;
		
		private string _TrackingInfo;
		
		private string _VehicleNumber;
		
		private System.Nullable<long> _VTId;
		
		private System.Nullable<long> _VTDId;
		
		private string _FormatType;
		
		private string _TrackedDate;
		
		private string _TrackedTime;
		
		private string _LoadingDate;
		
		private string _Customer_Party;
		
		private string _TLocation;
		
		private string _FLocation;
		
		private string _ETLocation;
		
		private string _VehicleStatus;
		
		private string _PLocation;
		
		private string _TravelledDistance;
		
		private string _BalanceDistance;
		
		private string _TransitDate;
		
		private string _TransitDays;
		
		private string _ExtendTransitDate;
		
		private string _ExtendTransitTime;
		
		private string _ReportingDate;
		
		private string _UnloadingDate;
		
		private string _TP_TBB;
		
		private string _TRANSIT;
		
		private string _LrNumber;
		
		private string _InvoiceNumber;
		
		private string _Material;
		
		private string _BranchName;
		
		private string _UserName;
		
		private string _UrgentTransit;
		
		private string _TotalKmAsPerOperator;
		
		private string _TotalKmAsPerGMAP;
		
		private string _TotalKmAsPerContract;
		
		private string _LoadingBranch;
		
		private string _ContactPerson;
		
		private string _ContactNumber;
		
		private string _BillingBranch;
		
		private string _DispatchRemarks;
		
		private int _Total;
		
		public SearchVehicleTrackingHistoryByBranchAndSubStatudIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNum", DbType="Int NOT NULL")]
		public int RowNum
		{
			get
			{
				return this._RowNum;
			}
			set
			{
				if ((this._RowNum != value))
				{
					this._RowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrackingInfo", DbType="NVarChar(MAX)")]
		public string TrackingInfo
		{
			get
			{
				return this._TrackingInfo;
			}
			set
			{
				if ((this._TrackingInfo != value))
				{
					this._TrackingInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleNumber", DbType="NVarChar(MAX)")]
		public string VehicleNumber
		{
			get
			{
				return this._VehicleNumber;
			}
			set
			{
				if ((this._VehicleNumber != value))
				{
					this._VehicleNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VTId", DbType="BigInt")]
		public System.Nullable<long> VTId
		{
			get
			{
				return this._VTId;
			}
			set
			{
				if ((this._VTId != value))
				{
					this._VTId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VTDId", DbType="BigInt")]
		public System.Nullable<long> VTDId
		{
			get
			{
				return this._VTDId;
			}
			set
			{
				if ((this._VTDId != value))
				{
					this._VTDId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormatType", DbType="NVarChar(MAX)")]
		public string FormatType
		{
			get
			{
				return this._FormatType;
			}
			set
			{
				if ((this._FormatType != value))
				{
					this._FormatType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrackedDate", DbType="NVarChar(MAX)")]
		public string TrackedDate
		{
			get
			{
				return this._TrackedDate;
			}
			set
			{
				if ((this._TrackedDate != value))
				{
					this._TrackedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrackedTime", DbType="NVarChar(MAX)")]
		public string TrackedTime
		{
			get
			{
				return this._TrackedTime;
			}
			set
			{
				if ((this._TrackedTime != value))
				{
					this._TrackedTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoadingDate", DbType="NVarChar(MAX)")]
		public string LoadingDate
		{
			get
			{
				return this._LoadingDate;
			}
			set
			{
				if ((this._LoadingDate != value))
				{
					this._LoadingDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_Party", DbType="NVarChar(MAX)")]
		public string Customer_Party
		{
			get
			{
				return this._Customer_Party;
			}
			set
			{
				if ((this._Customer_Party != value))
				{
					this._Customer_Party = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TLocation", DbType="NVarChar(MAX)")]
		public string TLocation
		{
			get
			{
				return this._TLocation;
			}
			set
			{
				if ((this._TLocation != value))
				{
					this._TLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLocation", DbType="NVarChar(MAX)")]
		public string FLocation
		{
			get
			{
				return this._FLocation;
			}
			set
			{
				if ((this._FLocation != value))
				{
					this._FLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ETLocation", DbType="NVarChar(MAX)")]
		public string ETLocation
		{
			get
			{
				return this._ETLocation;
			}
			set
			{
				if ((this._ETLocation != value))
				{
					this._ETLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleStatus", DbType="NVarChar(MAX)")]
		public string VehicleStatus
		{
			get
			{
				return this._VehicleStatus;
			}
			set
			{
				if ((this._VehicleStatus != value))
				{
					this._VehicleStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLocation", DbType="NVarChar(MAX)")]
		public string PLocation
		{
			get
			{
				return this._PLocation;
			}
			set
			{
				if ((this._PLocation != value))
				{
					this._PLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TravelledDistance", DbType="NVarChar(MAX)")]
		public string TravelledDistance
		{
			get
			{
				return this._TravelledDistance;
			}
			set
			{
				if ((this._TravelledDistance != value))
				{
					this._TravelledDistance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BalanceDistance", DbType="NVarChar(MAX)")]
		public string BalanceDistance
		{
			get
			{
				return this._BalanceDistance;
			}
			set
			{
				if ((this._BalanceDistance != value))
				{
					this._BalanceDistance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransitDate", DbType="NVarChar(MAX)")]
		public string TransitDate
		{
			get
			{
				return this._TransitDate;
			}
			set
			{
				if ((this._TransitDate != value))
				{
					this._TransitDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransitDays", DbType="NVarChar(MAX)")]
		public string TransitDays
		{
			get
			{
				return this._TransitDays;
			}
			set
			{
				if ((this._TransitDays != value))
				{
					this._TransitDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtendTransitDate", DbType="NVarChar(MAX)")]
		public string ExtendTransitDate
		{
			get
			{
				return this._ExtendTransitDate;
			}
			set
			{
				if ((this._ExtendTransitDate != value))
				{
					this._ExtendTransitDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtendTransitTime", DbType="NVarChar(MAX)")]
		public string ExtendTransitTime
		{
			get
			{
				return this._ExtendTransitTime;
			}
			set
			{
				if ((this._ExtendTransitTime != value))
				{
					this._ExtendTransitTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportingDate", DbType="NVarChar(MAX)")]
		public string ReportingDate
		{
			get
			{
				return this._ReportingDate;
			}
			set
			{
				if ((this._ReportingDate != value))
				{
					this._ReportingDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnloadingDate", DbType="NVarChar(MAX)")]
		public string UnloadingDate
		{
			get
			{
				return this._UnloadingDate;
			}
			set
			{
				if ((this._UnloadingDate != value))
				{
					this._UnloadingDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TP_TBB", DbType="NVarChar(MAX)")]
		public string TP_TBB
		{
			get
			{
				return this._TP_TBB;
			}
			set
			{
				if ((this._TP_TBB != value))
				{
					this._TP_TBB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANSIT", DbType="NVarChar(MAX)")]
		public string TRANSIT
		{
			get
			{
				return this._TRANSIT;
			}
			set
			{
				if ((this._TRANSIT != value))
				{
					this._TRANSIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LrNumber", DbType="NVarChar(MAX)")]
		public string LrNumber
		{
			get
			{
				return this._LrNumber;
			}
			set
			{
				if ((this._LrNumber != value))
				{
					this._LrNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="NVarChar(MAX)")]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this._InvoiceNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Material", DbType="NVarChar(MAX)")]
		public string Material
		{
			get
			{
				return this._Material;
			}
			set
			{
				if ((this._Material != value))
				{
					this._Material = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchName", DbType="NVarChar(MAX)")]
		public string BranchName
		{
			get
			{
				return this._BranchName;
			}
			set
			{
				if ((this._BranchName != value))
				{
					this._BranchName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(MAX)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrgentTransit", DbType="NVarChar(MAX)")]
		public string UrgentTransit
		{
			get
			{
				return this._UrgentTransit;
			}
			set
			{
				if ((this._UrgentTransit != value))
				{
					this._UrgentTransit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalKmAsPerOperator", DbType="NVarChar(MAX)")]
		public string TotalKmAsPerOperator
		{
			get
			{
				return this._TotalKmAsPerOperator;
			}
			set
			{
				if ((this._TotalKmAsPerOperator != value))
				{
					this._TotalKmAsPerOperator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalKmAsPerGMAP", DbType="NVarChar(MAX)")]
		public string TotalKmAsPerGMAP
		{
			get
			{
				return this._TotalKmAsPerGMAP;
			}
			set
			{
				if ((this._TotalKmAsPerGMAP != value))
				{
					this._TotalKmAsPerGMAP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalKmAsPerContract", DbType="NVarChar(MAX)")]
		public string TotalKmAsPerContract
		{
			get
			{
				return this._TotalKmAsPerContract;
			}
			set
			{
				if ((this._TotalKmAsPerContract != value))
				{
					this._TotalKmAsPerContract = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoadingBranch", DbType="NVarChar(MAX)")]
		public string LoadingBranch
		{
			get
			{
				return this._LoadingBranch;
			}
			set
			{
				if ((this._LoadingBranch != value))
				{
					this._LoadingBranch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPerson", DbType="NVarChar(MAX)")]
		public string ContactPerson
		{
			get
			{
				return this._ContactPerson;
			}
			set
			{
				if ((this._ContactPerson != value))
				{
					this._ContactPerson = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNumber", DbType="NVarChar(MAX)")]
		public string ContactNumber
		{
			get
			{
				return this._ContactNumber;
			}
			set
			{
				if ((this._ContactNumber != value))
				{
					this._ContactNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingBranch", DbType="NVarChar(MAX)")]
		public string BillingBranch
		{
			get
			{
				return this._BillingBranch;
			}
			set
			{
				if ((this._BillingBranch != value))
				{
					this._BillingBranch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DispatchRemarks", DbType="NVarChar(MAX)")]
		public string DispatchRemarks
		{
			get
			{
				return this._DispatchRemarks;
			}
			set
			{
				if ((this._DispatchRemarks != value))
				{
					this._DispatchRemarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int NOT NULL")]
		public int Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
	}
	
	public partial class CustomerWiseVehicleStatusCountResult
	{
		
		private string _VehicleSubStatusName;
		
		private System.Nullable<int> _VehicleStatusCount;
		
		private System.Nullable<long> _VehicleSubStatusId;
		
		private System.Nullable<long> _CustomerId;
		
		public CustomerWiseVehicleStatusCountResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleSubStatusName", DbType="NVarChar(100)")]
		public string VehicleSubStatusName
		{
			get
			{
				return this._VehicleSubStatusName;
			}
			set
			{
				if ((this._VehicleSubStatusName != value))
				{
					this._VehicleSubStatusName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleStatusCount", DbType="Int")]
		public System.Nullable<int> VehicleStatusCount
		{
			get
			{
				return this._VehicleStatusCount;
			}
			set
			{
				if ((this._VehicleStatusCount != value))
				{
					this._VehicleStatusCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleSubStatusId", DbType="BigInt")]
		public System.Nullable<long> VehicleSubStatusId
		{
			get
			{
				return this._VehicleSubStatusId;
			}
			set
			{
				if ((this._VehicleSubStatusId != value))
				{
					this._VehicleSubStatusId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerId", DbType="BigInt")]
		public System.Nullable<long> CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					this._CustomerId = value;
				}
			}
		}
	}
	
	public partial class SearchVehicleTrackingHistoryByCustomerAndSubStatudIdResult
	{
		
		private int _RowNum;
		
		private string _TrackingInfo;
		
		private string _VehicleNumber;
		
		private System.Nullable<long> _VTId;
		
		private System.Nullable<long> _VTDId;
		
		private string _FormatType;
		
		private string _TrackedDate;
		
		private string _TrackedTime;
		
		private string _LoadingDate;
		
		private string _Customer_Party;
		
		private string _TLocation;
		
		private string _FLocation;
		
		private string _ETLocation;
		
		private string _VehicleStatus;
		
		private string _PLocation;
		
		private string _TravelledDistance;
		
		private string _BalanceDistance;
		
		private string _TransitDate;
		
		private string _TransitDays;
		
		private string _ExtendTransitDate;
		
		private string _ExtendTransitTime;
		
		private string _ReportingDate;
		
		private string _UnloadingDate;
		
		private string _TP_TBB;
		
		private string _TRANSIT;
		
		private string _LrNumber;
		
		private string _InvoiceNumber;
		
		private string _Material;
		
		private string _BranchName;
		
		private string _UserName;
		
		private string _UrgentTransit;
		
		private string _TotalKmAsPerOperator;
		
		private string _TotalKmAsPerGMAP;
		
		private string _TotalKmAsPerContract;
		
		private string _LoadingBranch;
		
		private string _ContactPerson;
		
		private string _ContactNumber;
		
		private string _BillingBranch;
		
		private string _DispatchRemarks;
		
		private int _Total;
		
		public SearchVehicleTrackingHistoryByCustomerAndSubStatudIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNum", DbType="Int NOT NULL")]
		public int RowNum
		{
			get
			{
				return this._RowNum;
			}
			set
			{
				if ((this._RowNum != value))
				{
					this._RowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrackingInfo", DbType="NVarChar(MAX)")]
		public string TrackingInfo
		{
			get
			{
				return this._TrackingInfo;
			}
			set
			{
				if ((this._TrackingInfo != value))
				{
					this._TrackingInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleNumber", DbType="NVarChar(MAX)")]
		public string VehicleNumber
		{
			get
			{
				return this._VehicleNumber;
			}
			set
			{
				if ((this._VehicleNumber != value))
				{
					this._VehicleNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VTId", DbType="BigInt")]
		public System.Nullable<long> VTId
		{
			get
			{
				return this._VTId;
			}
			set
			{
				if ((this._VTId != value))
				{
					this._VTId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VTDId", DbType="BigInt")]
		public System.Nullable<long> VTDId
		{
			get
			{
				return this._VTDId;
			}
			set
			{
				if ((this._VTDId != value))
				{
					this._VTDId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormatType", DbType="NVarChar(MAX)")]
		public string FormatType
		{
			get
			{
				return this._FormatType;
			}
			set
			{
				if ((this._FormatType != value))
				{
					this._FormatType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrackedDate", DbType="NVarChar(MAX)")]
		public string TrackedDate
		{
			get
			{
				return this._TrackedDate;
			}
			set
			{
				if ((this._TrackedDate != value))
				{
					this._TrackedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrackedTime", DbType="NVarChar(MAX)")]
		public string TrackedTime
		{
			get
			{
				return this._TrackedTime;
			}
			set
			{
				if ((this._TrackedTime != value))
				{
					this._TrackedTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoadingDate", DbType="NVarChar(MAX)")]
		public string LoadingDate
		{
			get
			{
				return this._LoadingDate;
			}
			set
			{
				if ((this._LoadingDate != value))
				{
					this._LoadingDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_Party", DbType="NVarChar(MAX)")]
		public string Customer_Party
		{
			get
			{
				return this._Customer_Party;
			}
			set
			{
				if ((this._Customer_Party != value))
				{
					this._Customer_Party = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TLocation", DbType="NVarChar(MAX)")]
		public string TLocation
		{
			get
			{
				return this._TLocation;
			}
			set
			{
				if ((this._TLocation != value))
				{
					this._TLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLocation", DbType="NVarChar(MAX)")]
		public string FLocation
		{
			get
			{
				return this._FLocation;
			}
			set
			{
				if ((this._FLocation != value))
				{
					this._FLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ETLocation", DbType="NVarChar(MAX)")]
		public string ETLocation
		{
			get
			{
				return this._ETLocation;
			}
			set
			{
				if ((this._ETLocation != value))
				{
					this._ETLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleStatus", DbType="NVarChar(MAX)")]
		public string VehicleStatus
		{
			get
			{
				return this._VehicleStatus;
			}
			set
			{
				if ((this._VehicleStatus != value))
				{
					this._VehicleStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLocation", DbType="NVarChar(MAX)")]
		public string PLocation
		{
			get
			{
				return this._PLocation;
			}
			set
			{
				if ((this._PLocation != value))
				{
					this._PLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TravelledDistance", DbType="NVarChar(MAX)")]
		public string TravelledDistance
		{
			get
			{
				return this._TravelledDistance;
			}
			set
			{
				if ((this._TravelledDistance != value))
				{
					this._TravelledDistance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BalanceDistance", DbType="NVarChar(MAX)")]
		public string BalanceDistance
		{
			get
			{
				return this._BalanceDistance;
			}
			set
			{
				if ((this._BalanceDistance != value))
				{
					this._BalanceDistance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransitDate", DbType="NVarChar(MAX)")]
		public string TransitDate
		{
			get
			{
				return this._TransitDate;
			}
			set
			{
				if ((this._TransitDate != value))
				{
					this._TransitDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransitDays", DbType="NVarChar(MAX)")]
		public string TransitDays
		{
			get
			{
				return this._TransitDays;
			}
			set
			{
				if ((this._TransitDays != value))
				{
					this._TransitDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtendTransitDate", DbType="NVarChar(MAX)")]
		public string ExtendTransitDate
		{
			get
			{
				return this._ExtendTransitDate;
			}
			set
			{
				if ((this._ExtendTransitDate != value))
				{
					this._ExtendTransitDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtendTransitTime", DbType="NVarChar(MAX)")]
		public string ExtendTransitTime
		{
			get
			{
				return this._ExtendTransitTime;
			}
			set
			{
				if ((this._ExtendTransitTime != value))
				{
					this._ExtendTransitTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportingDate", DbType="NVarChar(MAX)")]
		public string ReportingDate
		{
			get
			{
				return this._ReportingDate;
			}
			set
			{
				if ((this._ReportingDate != value))
				{
					this._ReportingDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnloadingDate", DbType="NVarChar(MAX)")]
		public string UnloadingDate
		{
			get
			{
				return this._UnloadingDate;
			}
			set
			{
				if ((this._UnloadingDate != value))
				{
					this._UnloadingDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TP_TBB", DbType="NVarChar(MAX)")]
		public string TP_TBB
		{
			get
			{
				return this._TP_TBB;
			}
			set
			{
				if ((this._TP_TBB != value))
				{
					this._TP_TBB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANSIT", DbType="NVarChar(MAX)")]
		public string TRANSIT
		{
			get
			{
				return this._TRANSIT;
			}
			set
			{
				if ((this._TRANSIT != value))
				{
					this._TRANSIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LrNumber", DbType="NVarChar(MAX)")]
		public string LrNumber
		{
			get
			{
				return this._LrNumber;
			}
			set
			{
				if ((this._LrNumber != value))
				{
					this._LrNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="NVarChar(MAX)")]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this._InvoiceNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Material", DbType="NVarChar(MAX)")]
		public string Material
		{
			get
			{
				return this._Material;
			}
			set
			{
				if ((this._Material != value))
				{
					this._Material = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchName", DbType="NVarChar(MAX)")]
		public string BranchName
		{
			get
			{
				return this._BranchName;
			}
			set
			{
				if ((this._BranchName != value))
				{
					this._BranchName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(MAX)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrgentTransit", DbType="NVarChar(MAX)")]
		public string UrgentTransit
		{
			get
			{
				return this._UrgentTransit;
			}
			set
			{
				if ((this._UrgentTransit != value))
				{
					this._UrgentTransit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalKmAsPerOperator", DbType="NVarChar(MAX)")]
		public string TotalKmAsPerOperator
		{
			get
			{
				return this._TotalKmAsPerOperator;
			}
			set
			{
				if ((this._TotalKmAsPerOperator != value))
				{
					this._TotalKmAsPerOperator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalKmAsPerGMAP", DbType="NVarChar(MAX)")]
		public string TotalKmAsPerGMAP
		{
			get
			{
				return this._TotalKmAsPerGMAP;
			}
			set
			{
				if ((this._TotalKmAsPerGMAP != value))
				{
					this._TotalKmAsPerGMAP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalKmAsPerContract", DbType="NVarChar(MAX)")]
		public string TotalKmAsPerContract
		{
			get
			{
				return this._TotalKmAsPerContract;
			}
			set
			{
				if ((this._TotalKmAsPerContract != value))
				{
					this._TotalKmAsPerContract = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoadingBranch", DbType="NVarChar(MAX)")]
		public string LoadingBranch
		{
			get
			{
				return this._LoadingBranch;
			}
			set
			{
				if ((this._LoadingBranch != value))
				{
					this._LoadingBranch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPerson", DbType="NVarChar(MAX)")]
		public string ContactPerson
		{
			get
			{
				return this._ContactPerson;
			}
			set
			{
				if ((this._ContactPerson != value))
				{
					this._ContactPerson = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNumber", DbType="NVarChar(MAX)")]
		public string ContactNumber
		{
			get
			{
				return this._ContactNumber;
			}
			set
			{
				if ((this._ContactNumber != value))
				{
					this._ContactNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingBranch", DbType="NVarChar(MAX)")]
		public string BillingBranch
		{
			get
			{
				return this._BillingBranch;
			}
			set
			{
				if ((this._BillingBranch != value))
				{
					this._BillingBranch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DispatchRemarks", DbType="NVarChar(MAX)")]
		public string DispatchRemarks
		{
			get
			{
				return this._DispatchRemarks;
			}
			set
			{
				if ((this._DispatchRemarks != value))
				{
					this._DispatchRemarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int NOT NULL")]
		public int Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
	}
	
	public partial class BranchWiseVehicleTransitCountResult
	{
		
		private int _OnTime;
		
		private int _LateTransit;
		
		public BranchWiseVehicleTransitCountResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnTime", DbType="Int NOT NULL")]
		public int OnTime
		{
			get
			{
				return this._OnTime;
			}
			set
			{
				if ((this._OnTime != value))
				{
					this._OnTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LateTransit", DbType="Int NOT NULL")]
		public int LateTransit
		{
			get
			{
				return this._LateTransit;
			}
			set
			{
				if ((this._LateTransit != value))
				{
					this._LateTransit = value;
				}
			}
		}
	}
	
	public partial class GetBellCounterResult
	{
		
		private string _PageUrl;
		
		private string _PageName;
		
		private string _Controller;
		
		private long _RecoredId;
		
		private string _Remarks;
		
		private string _dayComment;
		
		private long _Id;
		
		public GetBellCounterResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageUrl", DbType="NVarChar(501)")]
		public string PageUrl
		{
			get
			{
				return this._PageUrl;
			}
			set
			{
				if ((this._PageUrl != value))
				{
					this._PageUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageName", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string PageName
		{
			get
			{
				return this._PageName;
			}
			set
			{
				if ((this._PageName != value))
				{
					this._PageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Controller", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Controller
		{
			get
			{
				return this._Controller;
			}
			set
			{
				if ((this._Controller != value))
				{
					this._Controller = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecoredId", DbType="BigInt NOT NULL")]
		public long RecoredId
		{
			get
			{
				return this._RecoredId;
			}
			set
			{
				if ((this._RecoredId != value))
				{
					this._RecoredId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(200)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dayComment", DbType="VarChar(42)")]
		public string dayComment
		{
			get
			{
				return this._dayComment;
			}
			set
			{
				if ((this._dayComment != value))
				{
					this._dayComment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
