#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManagerWeb.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FleetManager")]
	public partial class TrackerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTracker(Tracker instance);
    partial void UpdateTracker(Tracker instance);
    partial void DeleteTracker(Tracker instance);
    #endregion
		
		public TrackerDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FleetManagerConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TrackerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TrackerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TrackerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TrackerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tracker> Trackers
		{
			get
			{
				return this.GetTable<Tracker>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CountTracker")]
		public ISingleResult<CountTrackerResult> CountTracker()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<CountTrackerResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTrackerAll")]
		public ISingleResult<GetTrackerAllResult> GetTrackerAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetTrackerAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SearchTracker")]
		public ISingleResult<SearchTrackerResult> SearchTracker([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rows", DbType="Int")] System.Nullable<int> rows, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Page", DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sort", DbType="NVarChar(50)")] string sort, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TripStartDate", DbType="NVarChar(15)")] string tripStartDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TripEndDate", DbType="NVarChar(15)")] string tripEndDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LocationStartDate", DbType="NVarChar(15)")] string locationStartDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LocationEndDate", DbType="NVarChar(15)")] string locationEndDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search", DbType="NVarChar(50)")] string search, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="Int")] System.Nullable<int> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SysAdminRoleID", DbType="Int")] System.Nullable<int> sysAdminRoleID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminRoleID", DbType="Int")] System.Nullable<int> adminRoleID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rows, page, sort, tripStartDate, tripEndDate, locationStartDate, locationEndDate, search, userId, sysAdminRoleID, adminRoleID);
			return ((ISingleResult<SearchTrackerResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteTracker")]
		public ISingleResult<DeleteTrackerResult> DeleteTracker([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdList", DbType="NVarChar(MAX)")] string idList, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeletedBy", DbType="BigInt")] System.Nullable<long> deletedBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="BigInt")] System.Nullable<long> pageId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SysAdminRoleID", DbType="Int")] System.Nullable<int> sysAdminRoleID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminRoleID", DbType="Int")] System.Nullable<int> adminRoleID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idList, deletedBy, pageId, sysAdminRoleID, adminRoleID);
			return ((ISingleResult<DeleteTrackerResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SearchChangeLogTracker")]
		public ISingleResult<SearchChangeLogTrackerResult> SearchChangeLogTracker([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rows", DbType="Int")] System.Nullable<int> rows, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Page", DbType="Int")] System.Nullable<int> page, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search", DbType="NVarChar(500)")] string search, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sort", DbType="NVarChar(50)")] string sort, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TrackerID", DbType="Int")] System.Nullable<int> trackerID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rows, page, search, sort, trackerID);
			return ((ISingleResult<SearchChangeLogTrackerResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GenerateTrackerFormattedReport")]
		public ISingleResult<GenerateTrackerFormattedReportResult> GenerateTrackerFormattedReport([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(12)")] string tripStartDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(12)")] string tripEndDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> carId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tripStartDate, tripEndDate, carId);
			return ((ISingleResult<GenerateTrackerFormattedReportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTrackerById")]
		public ISingleResult<GetTrackerByIdResult> GetTrackerById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<GetTrackerByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertOrUpdateTracker")]
		public ISingleResult<InsertOrUpdateTrackerResult> InsertOrUpdateTracker(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Trip_Start", DbType="NVarChar(12)")] string trip_Start, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Trip_End", DbType="NVarChar(12)")] string trip_End, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Location_Start", DbType="NVarChar(100)")] string location_Start, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Location_End", DbType="NVarChar(100)")] string location_End, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Reason_Remarks", DbType="NVarChar(200)")] string reason_Remarks, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Km_Start", DbType="Int")] System.Nullable<int> km_Start, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Km_End", DbType="Int")] System.Nullable<int> km_End, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Km_Driven", DbType="Int")] System.Nullable<int> km_Driven, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fuel_Start", DbType="Int")] System.Nullable<int> fuel_Start, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fuel_End", DbType="Int")] System.Nullable<int> fuel_End, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Id", DbType="Int")] System.Nullable<int> user_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Entry_Method", DbType="NVarChar(1)")] string entry_Method, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Editable", DbType="Bit")] System.Nullable<bool> editable, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Active", DbType="Bit")] System.Nullable<bool> active, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageId", DbType="Int")] System.Nullable<int> pageId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Car_Id", DbType="Int")] System.Nullable<int> car_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Reason_Id", DbType="BigInt")] System.Nullable<long> reason_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_1", DbType="Int")] System.Nullable<int> id_1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_1_1", DbType="Int")] System.Nullable<int> id_1_1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanyId", DbType="BigInt")] System.Nullable<long> companyId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, trip_Start, trip_End, location_Start, location_End, reason_Remarks, km_Start, km_End, km_Driven, fuel_Start, fuel_End, user_Id, entry_Method, editable, active, pageId, car_Id, reason_Id, id_1, id_1_1, companyId);
			return ((ISingleResult<InsertOrUpdateTrackerResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tracker")]
	public partial class Tracker : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _Car_Id;
		
		private System.DateTime _Trip_Start;
		
		private System.DateTime _Trip_End;
		
		private string _Location_Start;
		
		private string _Location_End;
		
		private System.Nullable<long> _Reason_Id;
		
		private string _Reason_Remarks;
		
		private int _Km_Start;
		
		private int _Km_End;
		
		private int _Km_Driven;
		
		private int _Fuel_Start;
		
		private int _Fuel_End;
		
		private long _User_Id;
		
		private System.DateTime _Entry_Datetime;
		
		private string _Entry_Method;
		
		private bool _Editable;
		
		private bool _Active;
		
		private System.Nullable<int> _Id_1;
		
		private System.Nullable<int> _Id_1_1;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<int> _DeletedBy;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private System.Nullable<long> _CompanyId;
		
		private string _Registration;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCar_IdChanging(System.Nullable<int> value);
    partial void OnCar_IdChanged();
    partial void OnTrip_StartChanging(System.DateTime value);
    partial void OnTrip_StartChanged();
    partial void OnTrip_EndChanging(System.DateTime value);
    partial void OnTrip_EndChanged();
    partial void OnLocation_StartChanging(string value);
    partial void OnLocation_StartChanged();
    partial void OnLocation_EndChanging(string value);
    partial void OnLocation_EndChanged();
    partial void OnReason_IdChanging(System.Nullable<long> value);
    partial void OnReason_IdChanged();
    partial void OnReason_RemarksChanging(string value);
    partial void OnReason_RemarksChanged();
    partial void OnKm_StartChanging(int value);
    partial void OnKm_StartChanged();
    partial void OnKm_EndChanging(int value);
    partial void OnKm_EndChanged();
    partial void OnKm_DrivenChanging(int value);
    partial void OnKm_DrivenChanged();
    partial void OnFuel_StartChanging(int value);
    partial void OnFuel_StartChanged();
    partial void OnFuel_EndChanging(int value);
    partial void OnFuel_EndChanged();
    partial void OnUser_IdChanging(long value);
    partial void OnUser_IdChanged();
    partial void OnEntry_DatetimeChanging(System.DateTime value);
    partial void OnEntry_DatetimeChanged();
    partial void OnEntry_MethodChanging(string value);
    partial void OnEntry_MethodChanged();
    partial void OnEditableChanging(bool value);
    partial void OnEditableChanged();
    partial void OnActiveChanging(bool value);
    partial void OnActiveChanged();
    partial void OnId_1Changing(System.Nullable<int> value);
    partial void OnId_1Changed();
    partial void OnId_1_1Changing(System.Nullable<int> value);
    partial void OnId_1_1Changed();
    partial void OnIsDeletedChanging(System.Nullable<bool> value);
    partial void OnIsDeletedChanged();
    partial void OnDeletedByChanging(System.Nullable<int> value);
    partial void OnDeletedByChanged();
    partial void OnDeletedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnDeletedOnChanged();
    partial void OnCompanyIdChanging(System.Nullable<long> value);
    partial void OnCompanyIdChanged();
    partial void OnRegistrationChanging(string value);
    partial void OnRegistrationChanged();
    #endregion
		
		public Tracker()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Car_Id", DbType="Int")]
		public System.Nullable<int> Car_Id
		{
			get
			{
				return this._Car_Id;
			}
			set
			{
				if ((this._Car_Id != value))
				{
					this.OnCar_IdChanging(value);
					this.SendPropertyChanging();
					this._Car_Id = value;
					this.SendPropertyChanged("Car_Id");
					this.OnCar_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trip_Start", DbType="DateTime NOT NULL")]
		public System.DateTime Trip_Start
		{
			get
			{
				return this._Trip_Start;
			}
			set
			{
				if ((this._Trip_Start != value))
				{
					this.OnTrip_StartChanging(value);
					this.SendPropertyChanging();
					this._Trip_Start = value;
					this.SendPropertyChanged("Trip_Start");
					this.OnTrip_StartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trip_End", DbType="DateTime NOT NULL")]
		public System.DateTime Trip_End
		{
			get
			{
				return this._Trip_End;
			}
			set
			{
				if ((this._Trip_End != value))
				{
					this.OnTrip_EndChanging(value);
					this.SendPropertyChanging();
					this._Trip_End = value;
					this.SendPropertyChanged("Trip_End");
					this.OnTrip_EndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location_Start", DbType="NVarChar(100)")]
		public string Location_Start
		{
			get
			{
				return this._Location_Start;
			}
			set
			{
				if ((this._Location_Start != value))
				{
					this.OnLocation_StartChanging(value);
					this.SendPropertyChanging();
					this._Location_Start = value;
					this.SendPropertyChanged("Location_Start");
					this.OnLocation_StartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location_End", DbType="NVarChar(100)")]
		public string Location_End
		{
			get
			{
				return this._Location_End;
			}
			set
			{
				if ((this._Location_End != value))
				{
					this.OnLocation_EndChanging(value);
					this.SendPropertyChanging();
					this._Location_End = value;
					this.SendPropertyChanged("Location_End");
					this.OnLocation_EndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason_Id", DbType="BigInt")]
		public System.Nullable<long> Reason_Id
		{
			get
			{
				return this._Reason_Id;
			}
			set
			{
				if ((this._Reason_Id != value))
				{
					this.OnReason_IdChanging(value);
					this.SendPropertyChanging();
					this._Reason_Id = value;
					this.SendPropertyChanged("Reason_Id");
					this.OnReason_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason_Remarks", DbType="NVarChar(200)")]
		public string Reason_Remarks
		{
			get
			{
				return this._Reason_Remarks;
			}
			set
			{
				if ((this._Reason_Remarks != value))
				{
					this.OnReason_RemarksChanging(value);
					this.SendPropertyChanging();
					this._Reason_Remarks = value;
					this.SendPropertyChanged("Reason_Remarks");
					this.OnReason_RemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Km_Start", DbType="Int NOT NULL")]
		public int Km_Start
		{
			get
			{
				return this._Km_Start;
			}
			set
			{
				if ((this._Km_Start != value))
				{
					this.OnKm_StartChanging(value);
					this.SendPropertyChanging();
					this._Km_Start = value;
					this.SendPropertyChanged("Km_Start");
					this.OnKm_StartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Km_End", DbType="Int NOT NULL")]
		public int Km_End
		{
			get
			{
				return this._Km_End;
			}
			set
			{
				if ((this._Km_End != value))
				{
					this.OnKm_EndChanging(value);
					this.SendPropertyChanging();
					this._Km_End = value;
					this.SendPropertyChanged("Km_End");
					this.OnKm_EndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Km_Driven", DbType="Int NOT NULL")]
		public int Km_Driven
		{
			get
			{
				return this._Km_Driven;
			}
			set
			{
				if ((this._Km_Driven != value))
				{
					this.OnKm_DrivenChanging(value);
					this.SendPropertyChanging();
					this._Km_Driven = value;
					this.SendPropertyChanged("Km_Driven");
					this.OnKm_DrivenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fuel_Start", DbType="Int NOT NULL")]
		public int Fuel_Start
		{
			get
			{
				return this._Fuel_Start;
			}
			set
			{
				if ((this._Fuel_Start != value))
				{
					this.OnFuel_StartChanging(value);
					this.SendPropertyChanging();
					this._Fuel_Start = value;
					this.SendPropertyChanged("Fuel_Start");
					this.OnFuel_StartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fuel_End", DbType="Int NOT NULL")]
		public int Fuel_End
		{
			get
			{
				return this._Fuel_End;
			}
			set
			{
				if ((this._Fuel_End != value))
				{
					this.OnFuel_EndChanging(value);
					this.SendPropertyChanging();
					this._Fuel_End = value;
					this.SendPropertyChanged("Fuel_End");
					this.OnFuel_EndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="BigInt NOT NULL")]
		public long User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Datetime", DbType="DateTime NOT NULL")]
		public System.DateTime Entry_Datetime
		{
			get
			{
				return this._Entry_Datetime;
			}
			set
			{
				if ((this._Entry_Datetime != value))
				{
					this.OnEntry_DatetimeChanging(value);
					this.SendPropertyChanging();
					this._Entry_Datetime = value;
					this.SendPropertyChanged("Entry_Datetime");
					this.OnEntry_DatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Method", DbType="NVarChar(1)")]
		public string Entry_Method
		{
			get
			{
				return this._Entry_Method;
			}
			set
			{
				if ((this._Entry_Method != value))
				{
					this.OnEntry_MethodChanging(value);
					this.SendPropertyChanging();
					this._Entry_Method = value;
					this.SendPropertyChanged("Entry_Method");
					this.OnEntry_MethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editable", DbType="Bit NOT NULL")]
		public bool Editable
		{
			get
			{
				return this._Editable;
			}
			set
			{
				if ((this._Editable != value))
				{
					this.OnEditableChanging(value);
					this.SendPropertyChanging();
					this._Editable = value;
					this.SendPropertyChanged("Editable");
					this.OnEditableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_1", DbType="Int")]
		public System.Nullable<int> Id_1
		{
			get
			{
				return this._Id_1;
			}
			set
			{
				if ((this._Id_1 != value))
				{
					this.OnId_1Changing(value);
					this.SendPropertyChanging();
					this._Id_1 = value;
					this.SendPropertyChanged("Id_1");
					this.OnId_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_1_1", DbType="Int")]
		public System.Nullable<int> Id_1_1
		{
			get
			{
				return this._Id_1_1;
			}
			set
			{
				if ((this._Id_1_1 != value))
				{
					this.OnId_1_1Changing(value);
					this.SendPropertyChanging();
					this._Id_1_1 = value;
					this.SendPropertyChanged("Id_1_1");
					this.OnId_1_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedBy", DbType="Int")]
		public System.Nullable<int> DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this.OnDeletedByChanging(value);
					this.SendPropertyChanging();
					this._DeletedBy = value;
					this.SendPropertyChanged("DeletedBy");
					this.OnDeletedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this.OnDeletedOnChanging(value);
					this.SendPropertyChanging();
					this._DeletedOn = value;
					this.SendPropertyChanged("DeletedOn");
					this.OnDeletedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyId", DbType="BigInt")]
		public System.Nullable<long> CompanyId
		{
			get
			{
				return this._CompanyId;
			}
			set
			{
				if ((this._CompanyId != value))
				{
					this.OnCompanyIdChanging(value);
					this.SendPropertyChanging();
					this._CompanyId = value;
					this.SendPropertyChanged("CompanyId");
					this.OnCompanyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registration", DbType="NVarChar(100)")]
		public string Registration
		{
			get
			{
				return this._Registration;
			}
			set
			{
				if ((this._Registration != value))
				{
					this.OnRegistrationChanging(value);
					this.SendPropertyChanging();
					this._Registration = value;
					this.SendPropertyChanged("Registration");
					this.OnRegistrationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class CountTrackerResult
	{
		
		private System.Nullable<int> _Result;
		
		public CountTrackerResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int")]
		public System.Nullable<int> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class GetTrackerAllResult
	{
		
		private int _ID;
		
		private string _Trip_Start;
		
		private string _Trip_End;
		
		private string _Location_Start;
		
		private string _Location_End;
		
		private string _Reason_Remarks;
		
		private int _Km_Start;
		
		private int _Km_End;
		
		private int _Km_Driven;
		
		private int _Fuel_Start;
		
		private int _Fuel_End;
		
		private long _User_Id;
		
		private string _Entry_Datetime;
		
		private string _Entry_Method;
		
		private bool _Editable;
		
		private bool _Active;
		
		private System.Nullable<int> _Car_Id;
		
		private System.Nullable<long> _Reason_Id;
		
		private string _TripReasonName;
		
		private System.Nullable<int> _Id_1;
		
		private System.Nullable<int> _Id_1_1;
		
		public GetTrackerAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trip_Start", DbType="NVarChar(12)")]
		public string Trip_Start
		{
			get
			{
				return this._Trip_Start;
			}
			set
			{
				if ((this._Trip_Start != value))
				{
					this._Trip_Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trip_End", DbType="NVarChar(12)")]
		public string Trip_End
		{
			get
			{
				return this._Trip_End;
			}
			set
			{
				if ((this._Trip_End != value))
				{
					this._Trip_End = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location_Start", DbType="NVarChar(100)")]
		public string Location_Start
		{
			get
			{
				return this._Location_Start;
			}
			set
			{
				if ((this._Location_Start != value))
				{
					this._Location_Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location_End", DbType="NVarChar(100)")]
		public string Location_End
		{
			get
			{
				return this._Location_End;
			}
			set
			{
				if ((this._Location_End != value))
				{
					this._Location_End = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason_Remarks", DbType="NVarChar(200)")]
		public string Reason_Remarks
		{
			get
			{
				return this._Reason_Remarks;
			}
			set
			{
				if ((this._Reason_Remarks != value))
				{
					this._Reason_Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Km_Start", DbType="Int NOT NULL")]
		public int Km_Start
		{
			get
			{
				return this._Km_Start;
			}
			set
			{
				if ((this._Km_Start != value))
				{
					this._Km_Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Km_End", DbType="Int NOT NULL")]
		public int Km_End
		{
			get
			{
				return this._Km_End;
			}
			set
			{
				if ((this._Km_End != value))
				{
					this._Km_End = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Km_Driven", DbType="Int NOT NULL")]
		public int Km_Driven
		{
			get
			{
				return this._Km_Driven;
			}
			set
			{
				if ((this._Km_Driven != value))
				{
					this._Km_Driven = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fuel_Start", DbType="Int NOT NULL")]
		public int Fuel_Start
		{
			get
			{
				return this._Fuel_Start;
			}
			set
			{
				if ((this._Fuel_Start != value))
				{
					this._Fuel_Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fuel_End", DbType="Int NOT NULL")]
		public int Fuel_End
		{
			get
			{
				return this._Fuel_End;
			}
			set
			{
				if ((this._Fuel_End != value))
				{
					this._Fuel_End = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="BigInt NOT NULL")]
		public long User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this._User_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Datetime", DbType="NVarChar(12)")]
		public string Entry_Datetime
		{
			get
			{
				return this._Entry_Datetime;
			}
			set
			{
				if ((this._Entry_Datetime != value))
				{
					this._Entry_Datetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Method", DbType="NVarChar(1)")]
		public string Entry_Method
		{
			get
			{
				return this._Entry_Method;
			}
			set
			{
				if ((this._Entry_Method != value))
				{
					this._Entry_Method = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editable", DbType="Bit NOT NULL")]
		public bool Editable
		{
			get
			{
				return this._Editable;
			}
			set
			{
				if ((this._Editable != value))
				{
					this._Editable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Car_Id", DbType="Int")]
		public System.Nullable<int> Car_Id
		{
			get
			{
				return this._Car_Id;
			}
			set
			{
				if ((this._Car_Id != value))
				{
					this._Car_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason_Id", DbType="BigInt")]
		public System.Nullable<long> Reason_Id
		{
			get
			{
				return this._Reason_Id;
			}
			set
			{
				if ((this._Reason_Id != value))
				{
					this._Reason_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TripReasonName", DbType="NVarChar(50)")]
		public string TripReasonName
		{
			get
			{
				return this._TripReasonName;
			}
			set
			{
				if ((this._TripReasonName != value))
				{
					this._TripReasonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_1", DbType="Int")]
		public System.Nullable<int> Id_1
		{
			get
			{
				return this._Id_1;
			}
			set
			{
				if ((this._Id_1 != value))
				{
					this._Id_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_1_1", DbType="Int")]
		public System.Nullable<int> Id_1_1
		{
			get
			{
				return this._Id_1_1;
			}
			set
			{
				if ((this._Id_1_1 != value))
				{
					this._Id_1_1 = value;
				}
			}
		}
	}
	
	public partial class SearchTrackerResult
	{
		
		private int _RowNum;
		
		private long _Id;
		
		private string _TripStartDate;
		
		private string _TripEndDate;
		
		private string _LocationStart;
		
		private string _LocationEnd;
		
		private string _TripReasonName;
		
		private string _ReasonRemarks;
		
		private int _KmStart;
		
		private int _KmEnd;
		
		private int _KmDriven;
		
		private int _FuelStart;
		
		private int _FuelEnd;
		
		private string _Username;
		
		private string _EntryDatetime;
		
		private string _EntryMethod;
		
		private string _Editable;
		
		private string _Active;
		
		private System.Nullable<long> _CompanyId;
		
		private string _CompanyName;
		
		private int _Total;
		
		public SearchTrackerResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNum", DbType="Int NOT NULL")]
		public int RowNum
		{
			get
			{
				return this._RowNum;
			}
			set
			{
				if ((this._RowNum != value))
				{
					this._RowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TripStartDate", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string TripStartDate
		{
			get
			{
				return this._TripStartDate;
			}
			set
			{
				if ((this._TripStartDate != value))
				{
					this._TripStartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TripEndDate", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string TripEndDate
		{
			get
			{
				return this._TripEndDate;
			}
			set
			{
				if ((this._TripEndDate != value))
				{
					this._TripEndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationStart", DbType="NVarChar(100)")]
		public string LocationStart
		{
			get
			{
				return this._LocationStart;
			}
			set
			{
				if ((this._LocationStart != value))
				{
					this._LocationStart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationEnd", DbType="NVarChar(100)")]
		public string LocationEnd
		{
			get
			{
				return this._LocationEnd;
			}
			set
			{
				if ((this._LocationEnd != value))
				{
					this._LocationEnd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TripReasonName", DbType="NVarChar(50)")]
		public string TripReasonName
		{
			get
			{
				return this._TripReasonName;
			}
			set
			{
				if ((this._TripReasonName != value))
				{
					this._TripReasonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReasonRemarks", DbType="NVarChar(200)")]
		public string ReasonRemarks
		{
			get
			{
				return this._ReasonRemarks;
			}
			set
			{
				if ((this._ReasonRemarks != value))
				{
					this._ReasonRemarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KmStart", DbType="Int NOT NULL")]
		public int KmStart
		{
			get
			{
				return this._KmStart;
			}
			set
			{
				if ((this._KmStart != value))
				{
					this._KmStart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KmEnd", DbType="Int NOT NULL")]
		public int KmEnd
		{
			get
			{
				return this._KmEnd;
			}
			set
			{
				if ((this._KmEnd != value))
				{
					this._KmEnd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KmDriven", DbType="Int NOT NULL")]
		public int KmDriven
		{
			get
			{
				return this._KmDriven;
			}
			set
			{
				if ((this._KmDriven != value))
				{
					this._KmDriven = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FuelStart", DbType="Int NOT NULL")]
		public int FuelStart
		{
			get
			{
				return this._FuelStart;
			}
			set
			{
				if ((this._FuelStart != value))
				{
					this._FuelStart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FuelEnd", DbType="Int NOT NULL")]
		public int FuelEnd
		{
			get
			{
				return this._FuelEnd;
			}
			set
			{
				if ((this._FuelEnd != value))
				{
					this._FuelEnd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDatetime", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string EntryDatetime
		{
			get
			{
				return this._EntryDatetime;
			}
			set
			{
				if ((this._EntryDatetime != value))
				{
					this._EntryDatetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryMethod", DbType="NVarChar(1)")]
		public string EntryMethod
		{
			get
			{
				return this._EntryMethod;
			}
			set
			{
				if ((this._EntryMethod != value))
				{
					this._EntryMethod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editable", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string Editable
		{
			get
			{
				return this._Editable;
			}
			set
			{
				if ((this._Editable != value))
				{
					this._Editable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyId", DbType="BigInt")]
		public System.Nullable<long> CompanyId
		{
			get
			{
				return this._CompanyId;
			}
			set
			{
				if ((this._CompanyId != value))
				{
					this._CompanyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="NVarChar(100)")]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this._CompanyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int NOT NULL")]
		public int Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
	}
	
	public partial class DeleteTrackerResult
	{
		
		private int _TotalReference;
		
		private string _Name;
		
		public DeleteTrackerResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalReference", DbType="Int NOT NULL")]
		public int TotalReference
		{
			get
			{
				return this._TotalReference;
			}
			set
			{
				if ((this._TotalReference != value))
				{
					this._TotalReference = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class SearchChangeLogTrackerResult
	{
		
		private int _RowNum;
		
		private int _Id;
		
		private string _AuditComments;
		
		private int _TrackerId;
		
		private System.DateTime _Trip_Start;
		
		private System.DateTime _Trip_End;
		
		private string _Location_Start;
		
		private string _Location_End;
		
		private System.Nullable<long> _Reason_Id;
		
		private string _Reason_Remarks;
		
		private int _Km_Start;
		
		private int _Km_End;
		
		private int _Km_Driven;
		
		private int _Fuel_Start;
		
		private int _Fuel_End;
		
		private string _Entry_Method;
		
		private bool _Editable;
		
		private bool _Active;
		
		private System.Nullable<int> _Id_1;
		
		private System.Nullable<int> _Id_1_1;
		
		private long _CompanyId;
		
		private long _ModifiedBy;
		
		private System.DateTime _ModifiedOn;
		
		private int _Total;
		
		public SearchChangeLogTrackerResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNum", DbType="Int NOT NULL")]
		public int RowNum
		{
			get
			{
				return this._RowNum;
			}
			set
			{
				if ((this._RowNum != value))
				{
					this._RowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuditComments", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AuditComments
		{
			get
			{
				return this._AuditComments;
			}
			set
			{
				if ((this._AuditComments != value))
				{
					this._AuditComments = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrackerId", DbType="Int NOT NULL")]
		public int TrackerId
		{
			get
			{
				return this._TrackerId;
			}
			set
			{
				if ((this._TrackerId != value))
				{
					this._TrackerId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trip_Start", DbType="DateTime NOT NULL")]
		public System.DateTime Trip_Start
		{
			get
			{
				return this._Trip_Start;
			}
			set
			{
				if ((this._Trip_Start != value))
				{
					this._Trip_Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trip_End", DbType="DateTime NOT NULL")]
		public System.DateTime Trip_End
		{
			get
			{
				return this._Trip_End;
			}
			set
			{
				if ((this._Trip_End != value))
				{
					this._Trip_End = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location_Start", DbType="NVarChar(100)")]
		public string Location_Start
		{
			get
			{
				return this._Location_Start;
			}
			set
			{
				if ((this._Location_Start != value))
				{
					this._Location_Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location_End", DbType="NVarChar(100)")]
		public string Location_End
		{
			get
			{
				return this._Location_End;
			}
			set
			{
				if ((this._Location_End != value))
				{
					this._Location_End = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason_Id", DbType="BigInt")]
		public System.Nullable<long> Reason_Id
		{
			get
			{
				return this._Reason_Id;
			}
			set
			{
				if ((this._Reason_Id != value))
				{
					this._Reason_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason_Remarks", DbType="NVarChar(200)")]
		public string Reason_Remarks
		{
			get
			{
				return this._Reason_Remarks;
			}
			set
			{
				if ((this._Reason_Remarks != value))
				{
					this._Reason_Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Km_Start", DbType="Int NOT NULL")]
		public int Km_Start
		{
			get
			{
				return this._Km_Start;
			}
			set
			{
				if ((this._Km_Start != value))
				{
					this._Km_Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Km_End", DbType="Int NOT NULL")]
		public int Km_End
		{
			get
			{
				return this._Km_End;
			}
			set
			{
				if ((this._Km_End != value))
				{
					this._Km_End = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Km_Driven", DbType="Int NOT NULL")]
		public int Km_Driven
		{
			get
			{
				return this._Km_Driven;
			}
			set
			{
				if ((this._Km_Driven != value))
				{
					this._Km_Driven = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fuel_Start", DbType="Int NOT NULL")]
		public int Fuel_Start
		{
			get
			{
				return this._Fuel_Start;
			}
			set
			{
				if ((this._Fuel_Start != value))
				{
					this._Fuel_Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fuel_End", DbType="Int NOT NULL")]
		public int Fuel_End
		{
			get
			{
				return this._Fuel_End;
			}
			set
			{
				if ((this._Fuel_End != value))
				{
					this._Fuel_End = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Method", DbType="NVarChar(1)")]
		public string Entry_Method
		{
			get
			{
				return this._Entry_Method;
			}
			set
			{
				if ((this._Entry_Method != value))
				{
					this._Entry_Method = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editable", DbType="Bit NOT NULL")]
		public bool Editable
		{
			get
			{
				return this._Editable;
			}
			set
			{
				if ((this._Editable != value))
				{
					this._Editable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_1", DbType="Int")]
		public System.Nullable<int> Id_1
		{
			get
			{
				return this._Id_1;
			}
			set
			{
				if ((this._Id_1 != value))
				{
					this._Id_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_1_1", DbType="Int")]
		public System.Nullable<int> Id_1_1
		{
			get
			{
				return this._Id_1_1;
			}
			set
			{
				if ((this._Id_1_1 != value))
				{
					this._Id_1_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyId", DbType="BigInt NOT NULL")]
		public long CompanyId
		{
			get
			{
				return this._CompanyId;
			}
			set
			{
				if ((this._CompanyId != value))
				{
					this._CompanyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="BigInt NOT NULL")]
		public long ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this._ModifiedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedOn", DbType="DateTime NOT NULL")]
		public System.DateTime ModifiedOn
		{
			get
			{
				return this._ModifiedOn;
			}
			set
			{
				if ((this._ModifiedOn != value))
				{
					this._ModifiedOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int NOT NULL")]
		public int Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
	}
	
	public partial class GenerateTrackerFormattedReportResult
	{
		
		private int _Id;
		
		private System.Nullable<int> _Car_Id;
		
		private string _Desc;
		
		private System.DateTime _Trip_Start;
		
		private System.DateTime _Trip_End;
		
		private string _Location_Start;
		
		private string _Location_End;
		
		private string _TripReasonName;
		
		private string _Reason_Remarks;
		
		private int _Km_Start;
		
		private int _Km_End;
		
		private int _Km_Driven;
		
		public GenerateTrackerFormattedReportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Car_Id", DbType="Int")]
		public System.Nullable<int> Car_Id
		{
			get
			{
				return this._Car_Id;
			}
			set
			{
				if ((this._Car_Id != value))
				{
					this._Car_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Desc]", Storage="_Desc", DbType="NVarChar(50)")]
		public string Desc
		{
			get
			{
				return this._Desc;
			}
			set
			{
				if ((this._Desc != value))
				{
					this._Desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trip_Start", DbType="DateTime NOT NULL")]
		public System.DateTime Trip_Start
		{
			get
			{
				return this._Trip_Start;
			}
			set
			{
				if ((this._Trip_Start != value))
				{
					this._Trip_Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trip_End", DbType="DateTime NOT NULL")]
		public System.DateTime Trip_End
		{
			get
			{
				return this._Trip_End;
			}
			set
			{
				if ((this._Trip_End != value))
				{
					this._Trip_End = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location_Start", DbType="NVarChar(100)")]
		public string Location_Start
		{
			get
			{
				return this._Location_Start;
			}
			set
			{
				if ((this._Location_Start != value))
				{
					this._Location_Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location_End", DbType="NVarChar(100)")]
		public string Location_End
		{
			get
			{
				return this._Location_End;
			}
			set
			{
				if ((this._Location_End != value))
				{
					this._Location_End = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TripReasonName", DbType="NVarChar(50)")]
		public string TripReasonName
		{
			get
			{
				return this._TripReasonName;
			}
			set
			{
				if ((this._TripReasonName != value))
				{
					this._TripReasonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason_Remarks", DbType="NVarChar(200)")]
		public string Reason_Remarks
		{
			get
			{
				return this._Reason_Remarks;
			}
			set
			{
				if ((this._Reason_Remarks != value))
				{
					this._Reason_Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Km_Start", DbType="Int NOT NULL")]
		public int Km_Start
		{
			get
			{
				return this._Km_Start;
			}
			set
			{
				if ((this._Km_Start != value))
				{
					this._Km_Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Km_End", DbType="Int NOT NULL")]
		public int Km_End
		{
			get
			{
				return this._Km_End;
			}
			set
			{
				if ((this._Km_End != value))
				{
					this._Km_End = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Km_Driven", DbType="Int NOT NULL")]
		public int Km_Driven
		{
			get
			{
				return this._Km_Driven;
			}
			set
			{
				if ((this._Km_Driven != value))
				{
					this._Km_Driven = value;
				}
			}
		}
	}
	
	public partial class GetTrackerByIdResult
	{
		
		private int _ID;
		
		private string _Trip_Start;
		
		private string _Trip_End;
		
		private string _Location_Start;
		
		private string _Location_End;
		
		private string _Reason_Remarks;
		
		private int _Km_Start;
		
		private int _Km_End;
		
		private int _Km_Driven;
		
		private int _Fuel_Start;
		
		private int _Fuel_End;
		
		private long _User_Id;
		
		private string _Entry_Datetime;
		
		private string _Entry_Method;
		
		private bool _Editable;
		
		private bool _Active;
		
		private System.Nullable<int> _Car_Id;
		
		private System.Nullable<long> _Reason_Id;
		
		private System.Nullable<int> _Id_1;
		
		private System.Nullable<int> _Id_1_1;
		
		private System.Nullable<long> _CompanyId;
		
		public GetTrackerByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trip_Start", DbType="NVarChar(12)")]
		public string Trip_Start
		{
			get
			{
				return this._Trip_Start;
			}
			set
			{
				if ((this._Trip_Start != value))
				{
					this._Trip_Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trip_End", DbType="NVarChar(12)")]
		public string Trip_End
		{
			get
			{
				return this._Trip_End;
			}
			set
			{
				if ((this._Trip_End != value))
				{
					this._Trip_End = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location_Start", DbType="NVarChar(100)")]
		public string Location_Start
		{
			get
			{
				return this._Location_Start;
			}
			set
			{
				if ((this._Location_Start != value))
				{
					this._Location_Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location_End", DbType="NVarChar(100)")]
		public string Location_End
		{
			get
			{
				return this._Location_End;
			}
			set
			{
				if ((this._Location_End != value))
				{
					this._Location_End = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason_Remarks", DbType="NVarChar(200)")]
		public string Reason_Remarks
		{
			get
			{
				return this._Reason_Remarks;
			}
			set
			{
				if ((this._Reason_Remarks != value))
				{
					this._Reason_Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Km_Start", DbType="Int NOT NULL")]
		public int Km_Start
		{
			get
			{
				return this._Km_Start;
			}
			set
			{
				if ((this._Km_Start != value))
				{
					this._Km_Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Km_End", DbType="Int NOT NULL")]
		public int Km_End
		{
			get
			{
				return this._Km_End;
			}
			set
			{
				if ((this._Km_End != value))
				{
					this._Km_End = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Km_Driven", DbType="Int NOT NULL")]
		public int Km_Driven
		{
			get
			{
				return this._Km_Driven;
			}
			set
			{
				if ((this._Km_Driven != value))
				{
					this._Km_Driven = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fuel_Start", DbType="Int NOT NULL")]
		public int Fuel_Start
		{
			get
			{
				return this._Fuel_Start;
			}
			set
			{
				if ((this._Fuel_Start != value))
				{
					this._Fuel_Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fuel_End", DbType="Int NOT NULL")]
		public int Fuel_End
		{
			get
			{
				return this._Fuel_End;
			}
			set
			{
				if ((this._Fuel_End != value))
				{
					this._Fuel_End = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="BigInt NOT NULL")]
		public long User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this._User_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Datetime", DbType="NVarChar(12)")]
		public string Entry_Datetime
		{
			get
			{
				return this._Entry_Datetime;
			}
			set
			{
				if ((this._Entry_Datetime != value))
				{
					this._Entry_Datetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Method", DbType="NVarChar(1)")]
		public string Entry_Method
		{
			get
			{
				return this._Entry_Method;
			}
			set
			{
				if ((this._Entry_Method != value))
				{
					this._Entry_Method = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editable", DbType="Bit NOT NULL")]
		public bool Editable
		{
			get
			{
				return this._Editable;
			}
			set
			{
				if ((this._Editable != value))
				{
					this._Editable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Car_Id", DbType="Int")]
		public System.Nullable<int> Car_Id
		{
			get
			{
				return this._Car_Id;
			}
			set
			{
				if ((this._Car_Id != value))
				{
					this._Car_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason_Id", DbType="BigInt")]
		public System.Nullable<long> Reason_Id
		{
			get
			{
				return this._Reason_Id;
			}
			set
			{
				if ((this._Reason_Id != value))
				{
					this._Reason_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_1", DbType="Int")]
		public System.Nullable<int> Id_1
		{
			get
			{
				return this._Id_1;
			}
			set
			{
				if ((this._Id_1 != value))
				{
					this._Id_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_1_1", DbType="Int")]
		public System.Nullable<int> Id_1_1
		{
			get
			{
				return this._Id_1_1;
			}
			set
			{
				if ((this._Id_1_1 != value))
				{
					this._Id_1_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyId", DbType="BigInt")]
		public System.Nullable<long> CompanyId
		{
			get
			{
				return this._CompanyId;
			}
			set
			{
				if ((this._CompanyId != value))
				{
					this._CompanyId = value;
				}
			}
		}
	}
	
	public partial class InsertOrUpdateTrackerResult
	{
		
		private int _InsertedId;
		
		public InsertOrUpdateTrackerResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertedId", DbType="Int NOT NULL")]
		public int InsertedId
		{
			get
			{
				return this._InsertedId;
			}
			set
			{
				if ((this._InsertedId != value))
				{
					this._InsertedId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
