<?xml version="1.0" encoding="utf-8"?><Database Name="FleetManager" Class="UserDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=NISHANT\SQL2016EXPRESS;Initial Catalog=FleetManager;Integrated Security=True;Pooling=False;Asynchronous Processing=True;MultipleActiveResultSets=False;Application Name=FleetManager" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FleetManagerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SurName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLogin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AssignBy" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SessionDurationHour" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordExpireOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UnsuccessfulLoginAttempt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_ActivityLog" Member="ActivityLogs" ThisKey="Id" OtherKey="UserId" Type="ActivityLog" />
    </Type>
  </Table>
  <Table Name="dbo.ActivityLog" Member="ActivityLogs">
    <Type Name="ActivityLog">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="PageId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="AuditComments" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TableName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsLoginSuccess" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RecordId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_ActivityLog" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.CountUser" Method="CountUser">
    <ElementType Name="CountUserResult">
      <Column Name="Result" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DeleteUser" Method="DeleteUser">
    <Parameter Name="IdList" Parameter="idList" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DeletedBy" Parameter="deletedBy" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="PageId" Parameter="pageId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="DeleteUserResult">
      <Column Name="TotalReference" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUserByEmailId" Method="GetUserByEmailId">
    <Parameter Name="EmailId" Parameter="emailId" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GetUserByEmailIdResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="EmailID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SurName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetBranchManagerByBranchId" Method="GetBranchManagerByBranchId">
    <Parameter Name="BranchId" Parameter="branchId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="GetBranchManagerByBranchIdResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAdminUsersByRoleId" Method="GetAdminUsersByRoleId">
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="GetAdminUsersByRoleIdResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SurName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUserAll" Method="GetUserAll">
    <ElementType Name="GetUserAllResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SurName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLogin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllUsersByCompany" Method="GetAllUsersByCompany">
    <Parameter Name="CompanyId" Parameter="companyId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ParentGroupId" Parameter="parentGroupId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="SysAdminRoleID" Parameter="sysAdminRoleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminRoleID" Parameter="adminRoleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAllUsersByCompanyResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUsersByGroup" Method="GetUsersByGroup">
    <Parameter Name="Rows" Parameter="rows" Type="System.Int32" DbType="Int" />
    <Parameter Name="Page" Parameter="page" Type="System.Int32" DbType="Int" />
    <Parameter Name="Search" Parameter="search" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Sort" Parameter="sort" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="GroupId" Parameter="groupId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="GetUsersByGroupResult">
      <Column Name="RowNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SurName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ValidateUserAndInsertActivityLog" Method="ValidateUserAndInsertActivityLog">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="PageId" Parameter="pageId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="TableName" Parameter="tableName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="IsUserLogin" Parameter="isUserLogin" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="ValidateUserAndInsertActivityLogResult">
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertOrUpdateUser" Method="InsertOrUpdateUser">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="BranchId" Parameter="branchId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SurName" Parameter="surName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="MobileNo" Parameter="mobileNo" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="EmailID" Parameter="emailID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="EmployeeCode" Parameter="employeeCode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsLogin" Parameter="isLogin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="PageId" Parameter="pageId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="AssignBy" Parameter="assignBy" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="SessionDurationHour" Parameter="sessionDurationHour" Type="System.Int32" DbType="Int" />
    <Parameter Name="UnsuccessfulLoginAttempt" Parameter="unsuccessfulLoginAttempt" Type="System.Int32" DbType="Int" />
    <Parameter Name="PasswordExpirationCount" Parameter="passwordExpirationCount" Type="System.Int32" DbType="Int" />
    <ElementType Name="InsertOrUpdateUserResult">
      <Column Name="InsertedId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.fnCheckIsUserBlock" Method="fnCheckIsUserBlock" IsComposable="true">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="fnCheckIsUserBlockResult">
      <Column Name="IsUserBlock" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsPasswordExpire" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUserTrackerPermission" Method="GetUserTrackerPermission">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="GetUserTrackerPermissionResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TripStartDate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TripEndDate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LocationStart" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LocationEnd" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TripReasonName" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReasonRemarks" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="KmStart" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="KmEnd" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="KmDriven" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FuelStart" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FuelEnd" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EntryDatetime" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EntryMethod" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Editable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EditColumn" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteColumn" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertOrUpdateUserTrackerPermissions" Method="InsertOrUpdateUserTrackerPermissions">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="TripStartDate" Parameter="tripStartDate" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="TripEndDate" Parameter="tripEndDate" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="LocationStart" Parameter="locationStart" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="LocationEnd" Parameter="locationEnd" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="TripReasonName" Parameter="tripReasonName" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ReasonRemarks" Parameter="reasonRemarks" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="KmStart" Parameter="kmStart" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="KmEnd" Parameter="kmEnd" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="KmDriven" Parameter="kmDriven" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FuelStart" Parameter="fuelStart" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FuelEnd" Parameter="fuelEnd" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Username" Parameter="username" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EntryDatetime" Parameter="entryDatetime" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EntryMethod" Parameter="entryMethod" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Editable" Parameter="editable" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Active" Parameter="active" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CompanyName" Parameter="companyName" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="EditColumn" Parameter="editColumn" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="DeleteColumn" Parameter="deleteColumn" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CreatedBy" Parameter="createdBy" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="InsertOrUpdateUserTrackerPermissionsResult">
      <Column Name="InsertedId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUsersofUser" Method="GetUsersofUser">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="GetUsersofUserResult">
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetUserById" Method="GetUserById">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="GetUserByIdResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UserBranchName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SurName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLogin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="VehicleDistributeId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="EmployeeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AssignBy" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="SessionDurationHour" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnsuccessfulLoginAttempt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordExpirationCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SearchUser" Method="SearchUser">
    <Parameter Name="Rows" Parameter="rows" Type="System.Int32" DbType="Int" />
    <Parameter Name="Page" Parameter="page" Type="System.Int32" DbType="Int" />
    <Parameter Name="Search" Parameter="search" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Sort" Parameter="sort" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SysAdminRoleID" Parameter="sysAdminRoleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminRoleID" Parameter="adminRoleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SearchUserResult">
      <Column Name="RowNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SurName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BranchName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLogin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AssignBy" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CompanyCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>